* SQL
** queries
- multicolumn search 
  select * from leadsets where (leadset, prodversion) in (select leadset, prodversion from orders where uniqnr = 172858)
  disable index with USE INDEX()
- subselect with EXISTS
  select distinct(leadset) from leadset_attributes a1 where workstep = 5 and not exists (select 1 from leadset_attributes a2 where a2.Leadset = a1.Leadset and a2.ProdVersion = a1.ProdVersion and a2.Workstep = a1.Workstep and a2.Attribute = 2)
- transpose without pivot
  SELECT t.userid,
         MAX(CASE WHEN t.fieldname = 'Username' THEN t.fieldvalue ELSE NULL END) AS Username,
         MAX(CASE WHEN t.fieldname = 'Password' THEN t.fieldvalue ELSE NULL END) AS Password,
         MAX(CASE WHEN t.fieldname = 'Email Address' THEN t.fieldvalue ELSE NULL END) AS Email
    FROM TABLE t
  GROUP BY t.userid
- select values from list not in table
SELECT i
FROM
(
    SELECT 1 AS i UNION SELECT 2 UNION SELECT 3 UNION SELECT 6 UNION SELECT 7
) AS mylistofids
LEFT JOIN mytable
ON mytable.id = i
WHERE mytable.id IS NULL;

or with temporary table
- delete with subquery
  wrap in additional subquery
  DELETE e.*
  FROM tableE e
  WHERE id IN (SELECT id
             FROM (SELECT id
                   FROM tableE
                   WHERE arg = 1 AND foo = 'bar') x);
** glossary
 - DML data manupilation language
 - DDL data defintion language
** MySQL
run it in linux with /usr/sbin/rcmysql 
{start|stop|status|reload|restart|try-restart|force-reload}
or /etc/inti.d/mysql

| description                                             | command                                                                                                                                                                                                                     |
|---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| get all variables                                       | SHOW VARIABLES (LIKE ...), of interest is e.g. character_set                                                                                                                                                                |
| time interval                                           | NOW() - INTERVAL 2 HOUR SECOND DAY etc.                                                                                                                                                                                     |
| create user                                             | CREATE USER 'jeffrey'@'localhost' IDENTIFIED BY 'mypass';                                                                                                                                                                   |
| use binary collate for case sensitive string comparison | select * from orders where leadset LIKE 's%' COLLATE utf8_bin                                                                                                                                                               |
| tables without primary key                              | select * from `tables` t where t.table_schema = 'diko' and table_type = 'base table' and table_name not in (select table_name from KEY_COLUMN_USAGE c where c.CONSTRAINT_SCHEMA = 'diko' and c.CONSTRAINT_NAME = 'primary') |
| all processes                                           | SHOW FULL PROCESSLIST;                                                                                                                                                                                                      |

import file
bin\mysqld.exe --defaults-file="c:\Program Files\MySQL\MySQL Server 5.7\bin\my.ini" --init-file=c:\tmp\create_user.sql
*** InnoDB
- create index allows concurrent DML, see http://dev.mysql.com/doc/refman/5.6/en/innodb-create-index-overview.html
- MySQL will not use indexes if you query the wrong data type
**** transactions
| innodb status     | show engine innodb status                    |
| show transactions | SELECT * FROM information_schema.innodb_trx; |
*** mysqldump
- export schema:
  mysqldump.exe -u diituser -p8932500 -h 142.120.60.114 -P 3306 -B diko --add-drop-database --add-drop-table -c --create-options --hex-blob --triggers --compress --quick --routines --no-data -r diko.sql
*** mysqlbinlog
mysqlbinlog.exe --base64-output=decode-rows -v <mysql-bin...> > binlogparsed
-v: Reconstruct row events and display them as commented SQL statements.
If this option is given twice (by passing in either "-vv" or "--verbose --verbose"),
the output includes comments to indicate column data types and some metadata,
and row query log events if so configured

decode-rows not for re-executing, https://dev.mysql.com/doc/refman/5.7/en/mysqlbinlog-row-events.html

--start-datetime or by log_pos
*** timeouts
- connect_timeout
during establishing session
- interactive_timeout
used for connections from interactive clients, CLIENT_INTERACTIVE option to mysql_real_connect()
- wait_timeout
timeout for idle non-interactive sessions
- net_read_timeout
wait for reading data from client
- net_write_timeout
wait for client to receive data
- lock_wait_timeout
*** performance schema
SELECT * FROM `performance_schema`.`events_statements_current
*** mysqladmin
| description                     | command                                  |
|---------------------------------+------------------------------------------|
| search for innodb to get memory | mysqladmin -r -i 1 -c 60 extended-status |
*** time zones
set on server and can be set per connection
timestamp column saves time in UTC
* Debugging
- disable just in time debugging with Visual Studio:
go to Tools -> Options -> Debugging -> Just-In-Time and disable VS as the JIT debugger.
(if not set in WER registry)
** WinDbg
- http://blogs.msdn.com/b/tess/archive/2008/02/04/net-debugging-demos-information-and-setup-instructions.aspx
- http://blogs.msdn.com/b/johan/archive/2007/01/11/how-to-install-windbg-and-get-your-first-memory-dump.aspx
*** General
  - all commands starting with . are from windbg
  - commands starting with ! are from some loaded extension
*** Installation
  - included in Debugging Tools for Windows
*** Setup
  - copy sos.dll from C:\Windows\Microsoft.NET\Framework\ (or Framework64) to windbg folder for .Net debugging
  - load it with .load sos
  - Create a folder where you want to cache all the symbol files. For example: "C:\Symbols"
  - Start windbg and open the dialogue to configure the symbol path by clicking File -> Symbol File Path
    srv*c:\symbols\public*http://msdl.microsoft.com/download/symbols
  - reload the dlls with .reload
  - if mscordacwks.dll cannot be loaded:
    this should show the load path:
    !sym noisy
    .symfix c:\mylocalsymcache
    .cordll -ve -u -l
    just copy the dll from the target pc to windbg folder and rename it to mscordacwks_AAA_AAA_2.0.50727.xxxx.dll,
    AAA is either x86 or AMD64, xxxx are the last digits of the version number
    lmv m mscorwks shows the include path for the dll
*** Commands
  | command                                                      | description                                                         |
  |--------------------------------------------------------------+---------------------------------------------------------------------|
  | .load                                                        | load extension, better to use loadby to load sos matching framework |
  | .loadby                                                      | .loadby sos mscorwks (for 3.5), .loadby sos clr (>3.5)              |
  | .symfix                                                      | load symbols                                                        |
  | .reload /f                                                   | reload symbols                                                      |
  | !printexception                                              | show ex in crashdump                                                |
  | !clrstack                                                    | managed call stack                                                  |
  | !CLRStack -p / -l /-a                                        | with parameters, locals or both                                     |
  | ~                                                            | all threads                                                         |
  | !threads                                                     | all managed threads (when sos loaded)                               |
  | ~<thread number> s                                           | activate thread                                                     |
  | !EEStack                                                     | Runs the DumpStack command on all threads in the process            |
  | k                                                            | view call stack                                                     |
  | !runaway                                                     | Shows time consumed by each thread.                                 |
  | !dso                                                         | show list of references that are still on the stack                 |
  | !do <Object>                                                 | show object info                                                    |
  | !da <Array>                                                  | show array info                                                     |
  | !DumpHeap                                                    | show all objects in the heap                                        |
  | !DumpHeap -stat -type Assembly                               | show assemblies in the heap                                         |
  | !DumpDomain                                                  | show all loaded assemblies                                          |
  | kp; !do <Object from mscorwks!RaiseTheExceptionInternalOnly> | shows exception object info.                                        |
  | !pe <Object>                                                 | shows exception info                                                |

*** Resources
https://blogs.msdn.microsoft.com/amb/2011/05/12/do-not-collect-32bit-process-dumps-with-64bit-task-manager/
ProcDump  https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx
** GDB
*** init file
    [[file:.gdbinit]
*** commands
- -args
 invoke program with arguments, specified with -
- break
 set breakpoint
- bt
 backtrace the calling stack
- c
 continue program
- n
 next line
- p
 print and/or set variable
- run
 run the program
- s, u
 step in, out
*** breakpoints
   - show with info break
   - disable <number>
*** pause process
   - Ctrl-C, in emacs Ctrl-C, Ctrl-C
     windows gui needs workaround in mingw console http://www.mingw.org/wiki/Workaround_for_GDB_Ctrl_C_Interrupt
*** print
   - p Function()
*** control
   - next next line in function
   - step next source code line
   - finish end of current function

* svn
** command line
*** Commands
  | command                                         | description                                   |
  |-------------------------------------------------+-----------------------------------------------|
  | svn diff -r... path                             | diff to revision ... in local copy            |
  | svnadmin dump --deltas <repo> > out.dump        | create dumpfile with deltas between revisions |
  | svnadmin load --force-uuid <newrepo> < out.dump | restore backup with unique identifier         |

*** diff for patch
- get diff from svn with diff -r rev1:rev2
  or diff -c rev

- emacs replace regex
  \(.*\)(revision 13286)^M -> \1(revision 13286)
  maybe the file has to be opened with (setq inhibit-eol-conversion t)
  
- run patch with
  patch -p0 < patchfile
* Windows
** DOS
*** compare files
comp: use with /N, else only filesize diff

*** registry
regsvr: register file in the windows registry, with /u unset key   
*** telnet
telnet client, call open $<$server$>$ to open a client, export DISPLAY IP:0
*** ftp
ftp client, login with ftp\_(IP), start with ftp $<$IP$>$, quit with bye, change to dir, bin, prompt, mget *;
*** cmd
  - start shell with C:$\backslash$WINDOWS$\backslash$system32$\backslash$cmd.exe /C "start" for multiple windows
  - start parameters: /V:ON: deactivate delayed resolving of variables, resolve them with !var!
  - supply /Y if a default answer is requested, may work, e.g. net use ... /Y
  - use '::' before command to save it but not run
*** nbtstat
find hostname from ip address: nbtstat -a
*** nslookup
    get all hosts from ip: nslookup ip
*** cacls
set access for file: cacls <file> /G <user:mode>, e.g. cacls dummy.txt /G Everyone:F; revert with /R
*** findstr
search for text in files with /S in subdirectories
*** net
    - show connections with net use
    - remove with net use /delete h:
    - connect with net use H: \\aphrodite\home * /USER:schwarzhuber
      * is prompt for password
      /Y for default prompt
    - get domain groups
      net user /domain 'username optional'
*** netstat
- show listening ports (admin rights for -b show executable)
  netstat -n -a -b
  netstat -ano for pid
*** send mail per cmd line
TELNET MAIL.THEIRDOMAIN.COM 25
ehlo mydomain.com
mail from:<martin9700@mydomain.com>
rcpt to:<recipient@theirdomain.com>
data
This is a test, please do not respond
.
quit

to test relay change rcpt
rcpt to:<recipient@someotherdomain.com>
** Office
- disable cursor animation
HKEY_Current_User\Software\Microsoft\Office\16.0\Common\Graphics
Name: DisableAnimations
Type: REG_DWORD
Data: 1 (hexadecimal)
*** Excel
Hyperlinks relativ setzen mit Datei -> Eigenschaften -> Zusammenfassung: Hyperlink
**** settings
- set colon ; as delimiter for csv: Control Panel -> Region and Language -> Additional Settings
**** commands
- open vba editor: Alt+F11
**** Formulas
- references
  relativ: A1
  absolut: $A$1
  partial: $A1, A$1
- included in range, count
=ZÄHLENWENN($A$1:$A$110;E186)
**** csv to grid
- check for " for whole line
- data -> import csv
**** plotting
column has to be formatted to right data type
** Visual Studio
edit autoexp.dat for expanding and not stepping into in debugger
c:/Programme/Microsoft Visual Studio/Common/MSDev98/Bin/

TUString =<StringRep->Str,s>

[ExecutionControl] 
TUString::*=NoStepInto
CView::GetDocument=NoStepInto

c:/Programme/Microsoft Visual Studio 9.0/Common7/Packages/Debugger/

Makefile export:
wrong format for custom build of dll, use .$\backslash$LPPars not .LPPars\\
add path for DJGPP binaries
*** find-replace
new lines with regex + \r\n
*** search not working

  No matching text found to look in. 
  Find was stopped in progress.
  
  Press ctrl + break

*** Visual Studio 2008
**** how to run it with the 6.0 compiler
C++ settings : 		
linker setttings: 	
delete the reference to the vcprojects default port vcproj file
project right click tool build order -> deselect manifest
options -> max number of project builds: 1
comman
**** Visual Studio “Find” results in “No files were found to look in.
     Find stopped progress
     the workaround (as many of you noted) is to press Ctrl+Scroll Lock, Ctrl+Break, or the Break key alone
*** Visual Studio 6.0
**** shortcuts

- LineCut, LineOpenBelow, 
- CharLeft, CharRight, LineEnd, LineStart, LineUp, LineDown
- FindBackwardDialog, Find, FindInFiles

**** Profiling
switch profiling on in Settings: Linker: enable profiling\\%
start profiling in the menu Build: Profil\\%
merge pbt and pbo files with prep /m $<name>$\\%
create file with plist /t $<name>$

**** Visual SourceSafe
     - disable with HKEY_CURRENT_USER\Software\Microsoft\DevStudio\6.0\Source Control\Disabled
*** emacs keybinding > 2008
for 2019:
https://github.com/justcla/EmacsKeys
--> source code has to be edited also for the newest visual studio extension
    Download the Emacs emulation extension.

    Rename it from EmacsEmulations.vsix to EmacsEmulations.zip and unzip into a folder.

    Edit the <VisualStudio Version="10.0"> value on the extensions.vsixmanifest file (XML):

    <SupportedProducts>
        <VisualStudio Version="11.0">
        <Edition>Pro</Edition>
        </VisualStudio>
    </SupportedProducts>

    Note: Visual Studio 2013 works by setting Version="12.0". And VS Express can be used by setting <Edition>Express_All</Edition>
          Visual Studio 2015 "14.0"
    Zip the content inside the folder back up and rename it back to EmacsEmulations.vsix.
    Install the extension as the user who needs the bindings and not as administrator.
    Manually copy the Emacs.vsk file from the unzipped content of the extension to the Common7\IDE folder in the Visual Studio program directory (for which you will need elevated permissions).

*** command line compiler
cl /EHsc -DUNICODE -D_UNICODE <file including windows.h>.cpp user32.lib
*** subscription
visual studio downloads
msdn
https://my.visualstudio.com/Downloads/Featured
** remote desktop
- local drives are mapped to //tsclient
- for copy + paste enable all fields in local resources, and restart rdpclip.exe
- speed up connection with 15bit, background turned off
- back to fullscreen: ctrl alt break
- send ctrl alt del: ctrl alt end
** Win
   - disable explorer
     HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
     "Shell"="%ExePath%"
   - start cmd box as administrator
     runas /noprofile /user:mymachine\administrator cmd
     or with domain  /user:mydomain\admin
   - disable task manager
     Key: Software\Microsoft\Windows\CurrentVersion\Policies\System
     Name: DisableTaskMgr
     Type: REG_DWORD
     Value: 1=Enablethis key, that is DISABLE TaskManager
   - set group policy with gpedit.msc
     to set it up only for non-admin users (not XP): load mmc.exe, add gpedit as snapin
     select in Browse Dialog the users: non-Admin
   - policies are saved in the registry in 
     HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\
     HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\
   - edit registry of other user
     mark HKEY_USERS, File -> Load Hive
     load file ntuser.dat from user folder
     unload after edit
   - run PerfMon for performance monitoring
   - add items to send to senden an menu in documents and settings:user:sendto
   - Nicht genügend Serverspeicher vorhanden
     Not working: 
     HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management "LargeSystemCache" "1"
     HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\ "Size" "3"
     HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\ "IRPStackSize" "50"
   - kill processes
     list with tasklist, run as admin
     Taskkill /IM chrome.exe /F /T
   - default reply, no messagebox
     HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Error Message Instrument : EnableDefaultReply = 0
   - go to program and features
     Win+r, appwiz.cpl
   - boot manager
     - set options for vmware
       bcdedit /copy {current} /d "No Hyper-V" 
       The entry was successfully copied to {ff-23-113-824e-5c5144ea}. 
       bcdedit /set {ff-23-113-824e-5c5144ea} hypervisorlaunchtype off
       powershell: bcdedit /copy `{current`} /d "No Hyper-V"
   - reserve port win10
     netsh http add urlacl url=http://+:49550/ sddl=D:PAI(A;;FA;;;WD)
     netsh http add urlacl url=http://+:49550/ sddl=D:(A;;GX;;;S-1-1-0)
     netsh http delete urlacl url=http://+:49550/
   - caps lock to ctrl
     Windows Registry Editor Version 5.00
     [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
     "Scancode Map"=hex:00,00,00,00,00,00,00,00,02,00,00,00,1d,00,3a,00,00,00,00,00

     $hexified = "00,00,00,00,00,00,00,00,02,00,00,00,1d,00,3a,00,00,00,00,00".Split(',') | % { "0x$_"};
     $kbLayout = 'HKLM:\System\CurrentControlSet\Control\Keyboard Layout';
     New-ItemProperty -Path $kbLayout -Name "Scancode Map" -PropertyType Binary -Value ([byte[]]$hexified);
** Gadgets
*** basics
    - default gadgets are in C:\Program Files\Windows Sidebar\Gadgets
      copy one and rename folder and gadget.xml name
      zip and rename to .gadget
      install: did not work
    - folder %UserProfile%\AppData\Local\Microsoft\Windows Sidebar\Gadgets
** Visual Basic
   escape " with "", for a linebreak use \_
** .NET
PerformanceCounter cannot be used: in PerfMon all counters in Windows Workflow Foundation are not selectable; this seems to be the same reason why the resume layout after the EndInit of the PerformanceCounter fails
** Services
- start and control services with the \textbf{sc} command
- start net
  install a .Net service with installutil
  install: sc create CAO-COPLSapSebastian binPath= "C:\usr\schwarzhuber\COPL\bin\sap_gw.exe /ServiceName=CAO-COPLSapSebastian /gwFile=\"C:\usr\schwarzhuber\COPL\config\SAP_GW\SapGateway.xml\""
  change: sc config binPath= ...
- set start timeout
  1. Click Start, click Run, type regedit, and then click OK.
  2. Locate and then click the following registry subkey:
     HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control
  3. In the right pane, locate the ServicesPipeTimeout entry.
     Note: If the ServicesPipeTimeout entry does not exist, you must create it. To do this, follow these steps:
     On the Edit menu, point to New, and then click DWORD Value.
     Type ServicesPipeTimeout, and then press ENTER. 
  4. Right-click ServicesPipeTimeout, and then click Modify.
  5. Click Decimal, type 60000, and then click OK.
     This value represents the time in milliseconds before a service times out.
  6. Restart the computer.
** IIS

   -logfiles c:/inetpub/logs, set in IIS configuration, enable logging in Programs and Features -> turn Features on/off
   - HTTP Error 500.19
     0x80070005: Click the Security tab, and then click Edit.
     Click Add.
     In the Enter the object names to select box, type computername\IIS_IUSRS, click Check Names, and then click OK.
     Click to select the Read check box, and then click OK.
   - configuration
     %windir%\system32\inetsrv\config\applicationhost.config
     e.g. environment variables per pool in applicationPools
   - users
     https://stackoverflow.com/questions/14934006/iis-iusrs-and-iusr-permissions-in-iis8
     IIS AppPool\MyApplicationPoolName, IUSR, IIS_IUSRS
** disable telemetry data gathering
   http://superuser.com/questions/972501/how-to-stop-microsoft-from-gathering-telemetry-data-from-windows-7-8-and-8-1

** Wireshark
- Wireshark can't actually capture local packets on windows XP due to the nature of the windows TCP stack. When packets are sent and received on the same machine they don't seem to cross the network boundary that wireshark monitors.

    However there is a way around this, you can route the local traffic out via your network gateway (router) by setting up a (temporary) static route on your windows XP machine.

    Say your XP IP address is 192.168.0.2 and your gateway (router) address is 192.168.0.1 you could run the following command from windows XP command line to force all local traffic out and back across the network boundary, so wireshark could then track the data (note that wireshark will report packets twice in this scenario, once when they leave your pc and once when they return).

    route add 192.168.0.2 mask 255.255.255.255 192.168.0.1 metric 1

  ! First save the route for the ip address and add it afterwards again!
  add -p to make the change persistent

- filter for ip address and destination
  ip.addr == 142.120.20.133 & ip.dst == 142.120.60.20
** WER
set in HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting
*** path to dumps
\Debug: StoreLocation
or
%LOCALAPPDATA%\CrashDumps

** Sysinternals
*** check signing
sigcheck -a d:\tmp\DomainGroupsTester.exe
** Outlook
- set mail as read
File → Options → Advanced
Outlook panes section, click Reading Pane
Mark items as read when viewed in the Reading Pane and set interval
** File indexing
needed for outlook, can be disabled for hard drive to save space
https://superuser.com/questions/59864/stopping-microsoft-search-from-eating-my-hard-drive
    open services.msc
    Stop the Windows Search service (I was this far already).
    Rename C:\ProgramData\Microsoft\Search\Data\Applications\Windows\Windows.edb
    Start the Windows Search service
    The directory rebuilds Windows.edb (34 MB initial size in my case)
    Open Control Panel / Indexing Options
    Wait a long time for buttons to become enabled
    Click Modify
    Uncheck Users directory or whatever else you don't want indexed (I left Start Menu enabled because it's so small)
** virtual desktops
- disable animation
  System -> Advanced System Settings -> Performance:Settings
  deselect animate windows when minimizing and maximizing

** beyond compare
export at Session -> Text Compare Report
*** Define Unimportant Text
To ignore text differences, define a new Grammar element (what the text is), then mark it as unimportant.
use different name than existing ones, e.g. columns from 1 to xx
Navigate to the Session | Session Settings | Importance tab to set importance, Update session defaults
** WSL
- access
  path with \\wsl$, emacs shows it as //wsl$$/Ubuntu/home/<user>/
  from app also 'explorer.exe .' is possible as non-root user
- restart
  Get-Service LxssManager | Restart-Service
*** ubuntu
update system with do-release-upgrade
*** docker
install as listed on docker website for ubuntu
start demon with 'sudo dockerd'
* Thunderbird
** new mail
- switch text/html in new mail with create + shift

** virtual folder
   search for keywords -> create as virtual folder

* ruby
** ruby style
- callbacks
  def do_stuff(a,b,c)
    sum=a+b+c
    yield sum #<- can be checked with block_given?
  end

  #call with:
  do_stuff(a,b,c){|status_code| puts "did #{a}, ... #{status_code}"}
** basic
- find method
  <instance>.method(<:method_name>).source_location
*** rspec
    - run with rspec path/to/file.rb

** rails
speed up webrick without ReverseDNSLookup
*** basic
**** main layout
   <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   will produce an error, solution:

   http://stackoverflow.com/questions/12520456/execjsruntimeerror-on-windows-trying-to-follow-rubytutorial

My friend was attempting a Rails tutorial on Win 8 RTM a few months ago and ran into this error. Not sure if this issue exists in Windows 7 as well, but this may help.

Options:

1) Removing //= require_tree . / Ignoring the issue - As ColinR stated above, this line should not be causing an issue in the first place. There is an actual problem with ExecJS working properly with the JavaScript runtime on your system and removing this line is just ignoring that fact.

2) Installing Node.js / Running away - Many people seem to just end up installing Node.js and using that instead of the JavaScript runtime already on their system. While that is a valid option, it also requires additional software and only avoids the original issue, which is that ExecJS is not working properly with the JavaScript runtime already on your system. If the existing JavaScript runtime on your system is supposed to work, why not make it work instead of installing more software? According to the ExecJS creator, the runtime already built into Windows is in fact supported...

    ExecJS lets you run JavaScript code from Ruby. It automatically picks the best runtime available to evaluate your JavaScript program, then returns the result to you as a Ruby object.

    ExecJS supports these runtimes:

        therubyracer - Google V8 embedded within Ruby
        therubyrhino - Mozilla Rhino embedded within JRuby
        Node.js
        Apple JavaScriptCore - Included with Mac OS X
        Microsoft Windows Script Host (JScript)

    (from github.com/sstephenson/execjs#execjs )

3) Actually fixing the issue / Learning - Use the knowledge of options 1 and 2 to search for other solutions. I can't tell you how many webpages I closed upon seeing options 1 or 2 was the accepted solution before actually finding information about the root issue we were having. The only reason we kept looking was that we couldn't believe the Rails team would (1) insert a line of code in every scaffold generated project that caused an issue, or (2) require that we install additional software just to run that default line of code. And so we eventually arrived at a fix for our root issue (your miles may vary).

The Fix that worked for us: On the system having issues, find ExecJS's runtimes.rb file. It looks like this. Make a copy of the found file for backup. Open the original runtimes.rb for editing. Find the section that starts with the line JScript = ExternalRuntime.new(. In that section, on the line containing :command => "cscript //E:jscript //Nologo //U", - remove the //U only. Then on the line containing :encoding => 'UTF-16LE' # CScript with //U returns UTF-16LE - change UTF-16LE to UTF-8 . Save the changes to the file. This section of the file should now read:

JScript = ExternalRuntime.new(
    :name        => "JScript",
    :command     => "cscript //E:jscript //Nologo",
    :runner_path => ExecJS.root + "/support/jscript_runner.js",
    :encoding    => 'UTF-8' # CScript with //U returns UTF-16LE
)

Next, stop then restart your Rails server and refresh the page in your browser that produced the original error. Hopefully the page loads without error now. Here's the ExecJS issue thread where we originally posted our results: https://github.com/sstephenson/execjs/issues/81#issuecomment-9892952

If this did not fix the issue, you can always overwrite the modified runtimes.rb with the backup copy you (hopefully) made and everything will be back to square one. In that case, consider option 3 and keep searching. Let us know what eventually works for you.. unless it's removing the require_tree or installing node.js, there's plenty of that going around already. :)


*** running old rails
**** problem with bluecloth 2.2.0


     Run gem install bluecloth -v '2.2.0' if you haven't already

     Apply this patch on bluecloth.h file, on my machine it is located in

     H:\Ruby193\lib\ruby\gems\1.9.1\gems\bluecloth-2.2.0\ext\bluecloth.h

     Go to bluecloth 2.2.0 directory, for example

     H:\Ruby193\lib\ruby\gems\1.9.1\gems\bluecloth-2.2.0

     Run rake gem (this may require to install some additional gems).

     Then you should see .gem file created in

     H:\Ruby193\lib\ruby\gems\1.9.1\gems\bluecloth-2.2.0\pkg\bluecloth-2.2.0.gem

     Open this directory and install the patched gem:

     gem install bluecloth-2.2.0.gem --platform=ruby

     => will not work, but gem install works after that
**** problem with libv8
    used by therubyracer
    NOT: gem install libv8 -v '3.16.14.1' -- --with-system-v8
    take it out with: 
    gem 'therubyracer', "~>0.11", :platform => :ruby
    :platform :ruby will install only on unix
**** wrong version of rake
     use bundle exec rake
* VMWare
** disable beep: To turn it off for only one session, do the following:

   1. Click Start
   2. Click Run
   3. In the run box type
      net stop beep

To turn off the beep permanently, do the following:

1. Click Start
   2. Click Run
   3. In the run box type
      sc config beep start= disabled (please note the space after the = !!)

To change the status of the beep again, type any of the following in the run box:

    * sc config beep start= boot (for loading device driver by the boot loader)
    * sc config beep start= system (for loading device driver by the kernel initialization)
    * sc config beep start= auto (for starting service automatically at startup. Even when no one logs on)
    * sc config beep start= demand (for starting service manually (default, when no start parameter is specified))
    * sc config beep start= disabled (completely disables the service)
    * sc config beep start= delayed-auto (for starting service after other “auto” services are started)

** To disable ThinPrint on a View client, change the values of these registry keys as indicated:

    HKEY_CURRENT_USER Software VMware, Inc. VMware VDM Client RDP Settings RedirectPrinters = false
    HKLM SOFTWARE thinPrint TPAutoConnect ConnectToClient = DISABLED 

Notes:

    If the keys do not exist, create them with values of type STRING.
    You may have to reboot the client for the changes to take effect.
    This method disables ThinPrint on the client side only. The View Desktop can use ThinPrint to print when you connect to it from a different client computer. 

Additional Information
You may also disable ThinPrint within the virtual desktop by disabling the TP AutoConnect Service and TP VC Gateway Service.

To disable ThinPrint within the virtual desktop:

    Log in to the virtual machine.
    Open the Services console.
    Right-click the TP AutoConnect service.
    Click Properties.
    Under Service status, click Stop.
    Click the Startup type and click Disabled.
    Click OK.
    Repeat steps 1-7 for the TP VC Gateway service.
    Close the Services console. 
** Host USB device connection disabled
Try right clicking on one of the USB hubs and looking at the driver details. If usbfilter.sys is listed then open HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{36FC9E60-C465-11CF-8056-444553540000} and delete the UpperFilter, usbfilter pair. 
restart some times after change
** update vmware tools
dvd drive required
* C#/F#
repl with scriptcs/fsi
** folders
*** exe.config files
- XP: C:\Dokumente und Einstellungen\sebastian\Lokale Einstellungen\Anwendungsdaten\DiIT\
- Win7: C:\Users\schwarzhuber\AppData\Local\DiIT
** NUnit
*** basisc
    - console runner
      run with nunit-console.exe dllToTest
      creates result file in directory
** Uri Escaping
   pairs Uri.EscapeDataString and HttpUtility.UrlEncode,
   Uri.EscapeUriString and HttpUtility.UrlPathEncode

   Uri better, uses uppercase hex encoding
   see also http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding
** .Net Framework
*** exception in webclient
The specified registry key does not exist
Registry location: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework  
DWORD (32-bit) Value name: LegacyWPADSupport
Value data: 0
** Asynchronous programming
https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/
** Yield time slice
From https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/component-that-supports-the-event-based-asynchronous-pattern?view=netframework-4.7.2
Thread.Sleep(0) yields the reset of this time slice
https://stackoverflow.com/questions/2956961/difference-between-thread-sleep0-and-thread-yield
Thread.Sleep(0) cedes control to any ready thread of equal priority or keeps going on the current thread if there is none. Thread.Yield cedes control to any ready thread associated with the current processor.
Therefore spin wait with Sleep(1) if SpinWait not used http://joeduffyblog.com/2006/08/22/priorityinduced-starvation-why-sleep1-is-better-than-sleep0-and-the-windows-balance-set-manager/

** Ildasm
only included in debug/release with debug build:
// .custom instance void [mscorlib]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggableAttribute/DebuggingModes)
= ( 01 00 XX XX 00 00 00 00 )
optimized debug DLL 03 00
optimized release 02 00
non-optimized debug DLL 07 01
non-optimized release DLL 06 01
* emacs
** customize and start files
   - site-start.el is loaded first, cancel with --no-site-file

** build emacs
*** old verision
**** tools
    - mingw32: gcc, make (rename from mingw32-make)
    - GnuWin Packages: CoreUtils, FindUtils, libxpm (with src)
**** prebuild
    - copy simx.h to include dir
**** configure
    - configure.bat --with-gcc --cflags -ID:/tools/GnuWin32/include/ --without-png --without-jpeg --without-tiff --without-gif
**** make
*** new version
**** git repo
     - git clone git://git.savannah.gnu.org/emacs.git emacs
**** tools
     - mingw32: developer toolkit 
     - add the fstab file in the msys etc directory, http://www.mingw.org/wiki/Getting_Started#toc2
     - remove msys-texinfo and use the one from http://sourceforge.net/projects/ezwinports/files/
     - pckconfig from http://www.gtk.org/download/win32.php
**** prebuild
     - run ./autogen.sh
       then dos2unix configure.ac
       the again ./autogen.sh
**** build
     - release: CFLAGS='-O2' ../emacs/configure --prefix=/d/progra/c/emacsrelease
*** newer version
autoconf fails with:
' is already registered with AC_CONFIG_FILES.
-> set line endings for git to linux
** modes
*** artist mode
    for drawing asccii art, set unicode with (artist-select-line-char 128078)
*** org mode
| insert src block     | C-c C-,         |
| preserve line breaks | #+OPTIONS: \n:t |
|                      |                 |
**** ditaa
     - activate babel with ditaa
     - download ditaa.jar and install java jre to run
*** *Messages*
    set size of buffer with (setq message-log-max 5000)
*** hex with hexl-mode
     or hexl-find-file instead of find-file
*** which-function-mode
    display the current function name
*** lisp
ielm, eshell
** format
*** C++ Code
   - the C Label Minimum Indentation has to be set to 4 (with override style settings):
   (c-syntactic-indentation t) this will read the format from c-offsets-alist
   if no indentation is done, set it manually with C-c C-o
*** encoding
    change encoding of buffer with C-x RET f coding RET
*** carriage return
    (setq inhibit-eol-conversion t), otherwise windows file has only ^J in text mode
    https://lists.gnu.org/archive/html/help-gnu-emacs/2005-12/msg00548.html
** fonts
   - show all faces with M-x list-faces-display -> customize
   font family is fndry and fmly from xfontsel

** Windows
   Here's a Windows tip that I find invaluable for tools such as editors. Rather than associating Emacs with the particular file types you want to edit with it (because you may want to associate another application with them), add Emacs to your SendTo menu.

   - Open the folder where you installed Emacs and navigate to the bin directory.
   - Select runemacs.exe, click mouse-button-2 and select Create Shortcut. The new shortcut appears, highlighted.
   - Click mouse-button-2 again and select Cut (you're going to move it).
   - Move to the Start button and click mouse-button-2 to open the menu.
   - Select Explore, which should open Windows Explorer to the Start Menu folder.
    In the navigation pane, select the SendTo folder (usually just above the Start Menu folder) to open it.
    Within the SendTo folder, click mouse-button-2 and select Paste to insert the runemacs.exe shortcut.
    Rename the shortcut, if you like.

** misc commands
*** file layout/matching lines
**** occur
show regex in new buffer
M-x occur
can also be used during incremental search M-s o
**** how-many
searches from pos onwards
*** search for control characters
    C-q C-(control char), ^@ with C-Space, ^? with Backspace
*** environment variables
    (getenv "DS\_LOC") (setenv "DS\_LOC" "FTN")
*** set encoding
    C-x C-m f
*** remove complete line
    flush-line (opposite of keep-line)

*** replace in files
    M-x find-name-dired: you will be prompted for a root directory and a filename pattern.
    Press t to "toggle mark" for all files found.
    Press Q for "Query-Replace in Files...": you will be prompted for query/substitution regexps.
    To turn off the automatic switch of the letter case set case-replace to nil.
*** execute shell command
(shell-command-to-string "hostname")
*** get char info
    describe-char for character at point

*** pretty print xml
in sgml mode select region and run sgml-pretty-print
*** insert text at beginning of line
string-insert-rectangle. Set the mark (C-<SPC>) at the beginning of the first line you want to prefix, move the cursor to last line to be prefixed, and type M-x string-insert-rectangle <RET>
*** turn off lockfiles
do not create files #.<filename>: (setq create-lockfiles nil)
*** kill process
M-: (kill-process)
in buffer which has process running
otherwise list-processes, d on process or use process name as argument to kill process
(delete-process PROCESS) if kill is not working
proced will show processes for user
*** goto matching paren
C-M-n/C-M-p: list
C-M-f/C-M-b: sexp
*** print without quotes
in scratch (insert (fn))
*** insert in front of line/prefix
- string-insert-rectangle
- string-rectangle
- query-replace-regexp
^->..., not shown marked
*** capitalize/uppercase/lowercase
capitalize-word, capitalize-region, upcase-word, upcase-region
downcase-region
** Visual Studio in emacs
*** format
    for visual studio set (Basic Offset = 4) in programming languages C and (indent tabs mode = off) in editing indent. 
    Format is set in list

** elisp
   - you cannot execute buffer functions in scratch
   - CAR and CDR (could-er) are the two slots of a cons cell (an ordered pair) which refer to some lisp objects
   - numbers in a keymap represent decimal values of ascii control characters:\\%

   Dec. Code & Character
   9 & Tab 
   13 & carriage return 
   17 & C-q
   24 & C-# XXX: 
   27 & Esc
*** debug
edebug or debug
- M-x toggle-debug-on-error
- M-x edebug-defun
- enter with (debug)
** SQL Mode
in windows add the bin directory for mysql to the exec-path

** CSharp Mode

   when used in Linux some warning pops up because of uninitalize varible flymake:
   change is-flymake-loaded with check fboundp to boundp
   
   newer version of csharp-mode:
   (let ((is-flymake-enabled
   (and (boundp 'flymake-mode)
   flymake-mode)))

** Windows
   Here's a Windows tip that I find invaluable for tools such as editors. Rather than associating Emacs with the particular file types you want to edit with it (because you may want to associate another application with them), add Emacs to your SendTo menu.

   - Open the folder where you installed Emacs and navigate to the bin directory.
   - Select runemacs.exe, click mouse-button-2 and select Create Shortcut. The new shortcut appears, highlighted.
   - Click mouse-button-2 again and select Cut (you're going to move it).
   - Move to the Start button and click mouse-button-2 to open the menu.
   - Select Explore, which should open Windows Explorer to the Start Menu folder.
    In the navigation pane, select the SendTo folder (usually just above the Start Menu folder) to open it.
    Within the SendTo folder, click mouse-button-2 and select Paste to insert the runemacs.exe shortcut.
    Rename the shortcut, if you like.

** org mode
*** export only visible area
    C-c C-e C-v
*** odt export
    - export #+OPTIONS: H:10 num:t for template file, save as ott, use with #+ODT_STYLES_FILE: "D:/usr/schwarzhuber/projects/mine/example.ott"
    - set font in template under options, writer, default font only for this document
    - filename can be set with #+PROPERTY: EXPORT_FILE_NAME 2015_06_11_Neue_Funktionen_2, only if export subtree is used, C-s, change of property has to be activated with C-c C-c
*** misc
    - export table to csv with Tbl -> Export to File
    - file link
      file:<path to file> with two [ and two ]
    - save link
      C-c l: org-store-link
      will be available in C-c C-l: org-insert-link
    - structure template
      insert code block
      C-c C-,
      then choose s
    - no indentation below header
      (setq org-adapt-indentation nil)
** server-client
*** windows
start server, place script in shell:startup:
set HOME=%APPDATA%
del /Q "%HOME%/.emacs.d/server/*"
C:\tools\emacs\nt\runemacs.exe --daemon

start client:
C:\tools\emacs\lib-src\emacsclientw.exe -c -n -a runemacs.exe
** magit
*** blobs
open file with magit-find-file
used e.g. in blame-reverse
* Linux
** commands
- back quote command substitution: runs one command on the other, like ll `find . -print`. Could also be \$(cmd)

- list commands: run command1 \&\& then command2, if command1 returns 0, can also be used with ||, ; (sequentially), \& (asynchron)

- brace expansion: cmd {1,2,$\ldots$} every option in the braces separated by a comma gets extend and the cmd is run with the whole string (cp filename{,.bak})

- font show all fonts with xfontsel

- info show online help with 'info'

- find
  find . -follow -name "*.cfg" -exec grep -inHl 'mtbl' {} \; i: case insensitive, l: name of input file, H: filename, n: line number
  to start as few grep commands as possible GNU grep, otherwise last run not returned if only one file:
  find / -type f -exec grep -Hi 'the brown dog' {} +

  - two different files, maybe quoting of -name block necessary \( ... -o ... \):
    find . -type f -name '*.err' -o -name '*.pdf'
- grep
  skip directories with -d skip
- proc use 'proc show ZWN\_{}nprd' to start an agent in its directory or 'proc start YUL\_que'

- mounting 
  use mount for list of mounted devices, mounting table under /etc/fstab
  - mount windows share
    apt update
    apt-get install cifs-utils
    mount -t cifs -o username=<un>,password=<pw> //<host>/fsharp /home/student/fsharp

- ifconfig is in /sbin/, lists all ip addresses; (ipconfig)

- xev show key commands

- prompt display variable set through PS1
- setxkbmap set the keyboard mapping to de, us etc. (see next item)
- loadkeys load keys globally from lib, e.g. us -> us.map.gz, use showkeys to show them, only with access to /dev/console (see above item)
- basename/dirname chop path strings to names

- concatenate files to one
  cat file* >> toFile
  find . -type f -name '*.txt' -exec cat {} + >> output.file : + starts only one process

- append newline to end of file
  perl -0777 -i.original -pe 's/END;\n\$\$/END;\n\$\$\n/igs' Update*
- show ip
  ip addr show
  hostname -I
- telnet
  telnet <ip> <port>
- show blocked ports
  sudo /sbin/iptables -L -n
- show listening ports
  sudo netstat -tulpn
- diff two folders
  diff -ru src/ /f/restlib/src/
  or with new files N and ignore white space
  diff -Ewb -N -u -r /folder1 /folder2
- remove directory
  rm -r mydir, -rf to force
- echo output utf8
  enable backslash, write bytes
  echo -e 'hello\xff\xff'
- nc/netcat
  for tcp/udp connections
- cURL
  transfer data using various network protocols
  curl -H 'Client-ID: clientId \
       -X GET 'https://api.twitch.tv/helix/streams?game_id=33214'
       -X PUT "http://localhost:53266/API/v1/MaterialOrder/DispatchAcknowledged/4" -H  "accept: /*" -H  "Content-Type: application/json" -d "{\"userId\":\"user to\",\"applicatorId\":\"wac035"}"
  -i: show response header
  -X: use this method in all requests, also redirects
  -L: follow rd
  -v: verbose
  -k: insecure https access
  - ranges
    curl 'https://example.com/[1-9].html' -o save_#1.html
    curl 'https://example.com/{ham,cheese}.jpg' -o out_#1.jpg
  - in browser: copy as curl in dev tools
  -O: output to file
- wget
  non-interactive network retriever
- show system information
  uname -a
  less /proc/meminfo, /proc/cpuinfo etc.

- disk usage
  df, free
- dpkg
  debian package manager, only installs package without dep
- scp
  secure copy, copy from instance via ssh
- systemd
  sudo systemctl status docker.service
  sudo systemctl restart docker.service

  show log for service or other unit
  journalctl -u kubelet.service
- change owner of files/directory
  chown user:(group opt) -R (recursive) folder/file
  does not work with mounted windows partition, user has to be set in fstab/during mount
- file permissions
  chmod u=rwx,g=(+-)rx,o=r myfile
- getent
  show entries from name service switch libraries
  e.g. getent group
- replace in file
  sed -i 's/original/new/g' file.txt
- sudo
  run with -i with the current user's login shell
  to preserve environment -E, -s for set shell
- ripgrep rg
  -S/--smart-case
  -g/--glob file pattern
- ffmpeg
  ffmpeg -i sample.avi -ss 00:03:05 -to 00:05:45 -q:a 0 -map a sample.mp3
- dig
  dns lookup
- tcpdump
  show traffic on network
- linux version flavor
  cat /etc/os-release
  hostnamectl
- base64
  padding is different compared to node
*** apt
- apt list --installed/--upgradable
- apt search 'package'
- sudo apt purge thunderbird*
- apt-mark hold
  stop updates
  to continue
- update with
  sudo apt update
  sudo apt upgrade
** window managers
- old ones mwn, twn

- fvwm descendant from twn

- icewm also a lightweight wm with profiles
** ssh
*** commands
- add host to known hosts
  ssh-keyscan -H 192.168.1.162 >> ~/.ssh/known_hosts
- remove key from known_hosts
  ssh-keygen -R <host>
- ssh
  use 'ssh 142.120.61.41 -l root' to connect with root
  or ssh user@host
- no host check
  ssh -o StrictHostKeyChecking=no
- key generation
  [[*generate ssh keys][generate ssh keys]]
** distros
*** opensuse
https://en.opensuse.org/openSUSE:Cheat_sheet_13.1#Services
*** ubuntu/debian
https://wiki.debian.org/systemd/CheatSheet
- scaling
  gsettings set org.gnome.desktop.interface scaling-factor 2
  drag vmware window, then scaling is shown in display settings

*** fedora
https://fedoraproject.org/wiki/SysVinit_to_Systemd_Cheatsheet
* Vagrant
** config file
   - add local box with file:///C:/Users/...
   - port forwarding with config.vm.network :forwarded_port, guest: 3000, host: 3000 
* cygwin
** turn off beep
   home directory .inputrc
   set bell-style none
* mono
** build
   - csproj files with xbuild /p:Configuration=Debug x.csproj
** csproj
   - ToolsVersion sets framework
   - Bootstrapper entries are dependencies for click once setups 
* Tags
** setup
   - msys
     run find . -name "*.cs" -exec "D:\tools\emacs24.3\bin\etags.exe" -a {} ;
     creates a TAGS file
   - powershell
     dir -Include *.cpp,*.h -Recurse | %{$_.FullName} | C:\tools\emacs\lib-src\etags.exe -
** use
   visit-tags-table for TAGS file to use
   search tags with M-., C-u M-., C-u - M-.

* vi/vim/neovim
get 64bit from https://github.com/vim/vim-win32-installer/releases
** commands
   - unset an option with set no<option>
   - show whitespace: set list
   - set background color hi: Normal guibg=Grey90
   - reload file with e!
   - close buffer with bdelete
   - go to line :<num>
   - replace in file :%s/Search-Word/Replace-Word/gc, c for confirmation
     search for newline: \n, replace: \r
   - run in shell (external command) :! <cmd> (% for current file) or start :shell
   - run last external command :!!
   - run last command .
   - insert text in current buffer from file or command :r <file> :r ! <cmd>
   - shift text/shift block ::
     in visual mode: >, . if more lines were selected
     normal mode: >> for current line, 4>> for 4 lines
** colorscheme
   save it in .vim/colors
   add it in .vimrc with colorscheme <name>
** bell
   set it to visual bell
   set noeb vb t_vb=
** unicode support
add https://www.vim.org/scripts/script.php?script_id=789 to config file
** packages
put packages in folder
vim windows: ~/vimfiles/pack/bundle/start/
neovim: ~/.config/nvim/pack/bundle/start
* git
** basics
   - .gitignore for files which should not be shown in untracked files
   - add project to github
     create project on github
     git remote add origin https://github.com/cannero/monkey_interpreter_compiler.git
     git push -u origin master
   - on windows set credential.helper=manager if login to azure devops not possible
** commands
   - add: add files, redo if changed, -A adds all files, -u only modified and deleted files
   - commit: commit -m 'message', -a for all unstaged changes
   - diff
     --cached shows diff with staged files
     <commit> <commit> for difference between two commits
     compare to last version: @{1} <file>, short for HEAD@{1}
     compare to master: git diff origin/master -- [local-path]
     all changes between two commits, path can be also files: git diff commit1^..commit2 -- [<path>...]
     between two files: git diff --word-diff=color --word-diff-regex=. file1 file2, if in repo add --no-index
     -w ignore whitespace
     -U<n> n lines of context
   - log
     show last i commits with -n i
     short overview with files: --stat
     patch output of last two commits: -p -2
     log graph: --graph --decorate --pretty=oneline --abbrev-commit
     Only show commits adding or removing code matching the string: -S string
   - add to last commit
     git commit --amend --no-edit
     no-edit flag re-uses the last commit message
   - rename case insensitive folders
     git mv foldername tempname && git mv tempname folderName
   - create mbox file from commits, first commit not included
     git format-patch --stdout 7c46acb1..c8ee6573 > 01.3_15.3.patch
     for last commit git format-patch --stdout HEAD^
   - undo add
     git reset, git reset <file>
     if no head exists git rm --cached <added_file_to_undo>
   - To get an inclusive list of commits, just list the two references separated by a space. Your first reference should reference the previous commit with a tilda ~ and then be excluded which is denoted with a leading circumflex ^
     git rev-list --reverse ^<tag1>~ <tag2>
   - To list all files in a commit
     git diff-tree --no-commit-id --name-only -r bd61ad98
     --name-status instead for action
   - To revert single file before adding/everything
     git checkout c5f567~1 -- file1/to/restore file2/to/restore
     git checkout .
   - revert change from commit in one file
     git show some_commit_sha1 -- some_file.c | git apply -R
   - branch
     to show remote ones -r
     rename local branch: -m <oldname> <newname>, case sensitive -M
     rename local and remote:
     git branch -m <old_name> <new_name>
     git push <remote> --delete <old_name>
     # Or shorter way to delete remote branch [:]
     git push <remote> :<old_name>
     git push <remote> <new_name>
     git push <remote> -u <new_name>
   - cherry-pick
   - remove changes in all tracked files
     git checkout -f
   - remove untracked files git clean -f, test run git clean -nf, . for current directory
   - reset
     git reset --hard <HEAD/sha> or origin/branch
   - merge
     --no-ff to create a new commit without fast forward
   - stash
     add new entry with push -m
     list with stash list, stash show @{index}
     restore with stash apply --index n
   - status
     to not show untracked files: -uno
   - rev-parse, parents of commits
     first parent ref~, ref^
     second parent ref^2
     parent of parent ref~
     two commits back master~2
   - config
     show all entries: git config --list
     don't change line ending: git config --global core.autocrlf input
   - show/change remote origin/master or upstream
     show: git remote -v
     change: git remote set-url origin new.git.url/here
   - add second remote (upstream) for getting changes for fork
     git remote add upstream https://github.com/whoever/whatever.git
     git fetch upstream
     git checkout master
     git rebase upstream/master
     git push -f origin master
   - push
     after rebase push with --force-with-lease to check if remote has been updated in between
   - apply
     --stat to see changes in diff
     --check
     apply patch eiter with apply or am for signoff
   - update-git-for-windows
     windows version
** find when line was deleted
- git blame --reverse START.. file.ext
  --first-parent if multiple merges
- git log -S <string> path/to/file
  can also be run on directory
  -c -cc for combined merge
  also called pickaxe
** checkout only subdirectory
*** sparse checkout
- git init
- git remote add -f origin https://github.com/googlesamples/android-architecture
- git config core.sparseCheckout true
- echo "BasicRxJavaSample/" >> .git/info/sparse-checkout
  with powershell use ascii encoding
- git pull origin master
*** filter
git clone --filter
has to be supported by the server, still in work?
** credential.helper
*** manager for windows
git config --global credential.helper manager
newer: git config --global credential.helper manager-core
for azure devops, msys has not manager
https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/500
-> use windows build
*** store
git config --global credential.helper store
stores pwd after the next commit in ~/.git-credentials
* powershell
use this in the powershell profile, 'test-path $profile'
Import-Module PSReadLine
Set-PSReadLineOption -EditMode Emacs
** powershell core
- update
  iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"
** commands
   - info
     $host has Version property
     [Environment]::Is64BitProcess
   - Load a dll
     Add-Type -Path .$\backslash$DiIT.Misc.dll
   - get methods + members: [int] | Get-Member
   - call static methods with [int]::MaxValue
   - pipe to fl (Format-List) to get all properties
   - call method: $i = 30, $i.GetHashCode()
   - create a class
     $a = New-Object DiIT.Misc.LeadsetPV("sfasdf/122/3")
   - parameter switch
     set it with colon -parameter:$true
   - open registry key remotely
     $Reg = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey('LocalMachine', "coplds1")
     $RegKey= $Reg.OpenSubKey("SOFTWARE\DiIT\copl\Database")
   - get unique values from a csv file
     $leadsets = Import-Csv .\sft.csv -Delimiter ';'
     $dupLeadsets = $leadsets | Group {$_.Leadset} | where {$_.Count -gt 1}
     $dupLeadsets | select count, name > duplicate_leadsets.csv
   - get path for executable
     (Get-Command notepad.exe).Path
   - test for open port
     $ipaddress = IP_Address_Server
     $port = port
     $connection = New-Object System.Net.Sockets.TcpClient($ipaddress, $port)
     if ($connection.Connected) {
       Write-Host "Success"
     } else {
       Write-Host "Failed"
     }
   - base 64
     to:
     $Text = ‘This is a secret and should be hidden’
     $Bytes = [System.Text.Encoding]::Unicode.GetBytes($Text)
     $EncodedText =[Convert]::ToBase64String($Bytes)
     from:
     $DecodedText = [System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($EncodedText))
   - remove apps
     Get-AppxPackage *Microsoft.YourPhone* -AllUsers | Remove-AppxPackage
   - pipe file to stdin
     Get-Content -ReadCount 500 backup.sql | & psql --username=... db_name
     ReadCount for ps 5.0
     Start-Process "C:\Program Files\PostgreSQL\<version>\bin\psql.exe" '--username=... db_name' -RedirectStandardInput backup.sql -NoNewWindow -Wait
   - pipe stdout to file
     Out-File -FilePath C:\Services.txt
     -Append
   - tail file
     show the last two lines:
     Get-Content  filename -Tail 2
   - remoting
     Enter-PSSession -ComputerName <pcname>
     Invoke-Command -ComputerName <pcname> -ScriptBlock {hostname}
   - search for multiple file types
     -Recurse has to be set for -Include, -Filter allows only one type, dir is Get-ChildItem
     dir -Include *.cpp,*.h -Recurse
   - replace text in file
     $text = (Get-Content -Path "File" -ReadCount 0) -join "`n"
     $text -replace "oldName", "newName" -replace "oldName2", "newName2" | Set-Content -Path "newFile"
   - open tcp listener
     $Listener = [System.Net.Sockets.TcpListener]9999;
     $Listener.Start();
     while($true)
     {
       $client = $Listener.AcceptTcpClient();
       Write-Host "Connected!";
       $client.Close();
     }
   - uptime
     - Get-Uptime -Since
     - (gcim Win32_OperatingSystem).LastBootUpTime
   - test ip connection
     Test-NetConnection -Port 0000 -ComputerName ABC
   - cpu load
     $NumberOfLogicalProcessors=(Get-WmiObject -class Win32_processor | Measure-Object -Sum NumberOfLogicalProcessors).Sum
     (Get-Counter '\Process(*)\% Processor Time').Countersamples | Where cookedvalue -gt ($NumberOfLogicalProcessors*10) | Sort cookedvalue -Desc | ft -a instancename, @{Name='CPU %';Expr={[Math]::Round($_.CookedValue / $NumberOfLogicalProcessors)}}

*** format files output
    get-item .\* -Include *.dll, *.exe | where-object {$_.VersionInfo.CompanyName -eq "DiIT"} | sort {$_.VersionInfo.FileVersion} | ForEach-Object {$_.VersionInfo.FileVersion + " " + $_.Name}
* Redmine
  webrick has problems with reverse dns lookup, turn it off
** svn integration
   - enable SCM in Administration -> Repositories
   - enable WS for repository management
     use Web Service to udpate svn log on every commit
   - set the repository for every project
   - run ruby /path_to_redmine/redmine/script/rails runner "Repository.fetch_changesets" -e production
     to get the complete log the first time
     first call svn from the command line to set the svn user and password
   - set post-commit hook
* LibreOffice
** convert to pdf
   *LibreOffice should not run*
   in Windows only - not --
   soffice.exe -convert-to pdf Neue_Funktionen.odt -headless
   
** calc
*** sort/filter
    Data->Filter->AutoFilter
** impress
*** master
right click -> edit master
*** defaults
F11 (styles and formatting): image and presentation styles
-> right click edit styles
* GDB
** init file
   [[file:.gdbinit]
** commands
- -args
 invoke program with arguments, specified with -
- break
 set breakpoint
- bt
 backtrace the calling stack
- c
 continue program
- n
 next line
- p
 print and/or set variable
- run
 run the program
- s, u
 step in, out
* Gimp
  Create Transparent Background: Add Alpha Channel in Layers, select Select By Color Tool, click background, delete it
* msbuild
** structure
   a Project has different PropertyGroup, ItemGroup and Target elements
*** simple one
    <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
    <AssemblyName>MoqTests</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
    <Compile Include="Tests.cs"/>
    </ItemGroup>
    <Target Name="Build">
    <Csc Sources="@(Compile)" OutputAssembly="$(AssemblyName).exe"/>
    </Target>
    </Project>
*** extended
    <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
    where targets are defined
** references
   - http://msdn.microsoft.com/en-us/library/dd393574%28v=vs.100%29.aspx
   - http://msdn.microsoft.com/en-us/library/dd576348%28v=vs.100%29.aspx
   - Target Files: WindowsInstallationPath\Microsoft.NET\Framework\<version>\
* common
** start bios win8
   shift-click restart: advanced boot options
* GnuWin32
  - run download.bat
  - run install <directory>

* OOP
** Basics and Principles
- Encapsulate what varies
- Favor composition over inheritance: has-a is better than is-a; changeable during runtime
- Program to an interface not an implementation: model behavior in new abstract class, reusable and modifyable
- Strive for loosely coupled designs: objects can interact, but have very little knowledge of each other
- Open Closed Principle: Classes should be closed for modification but open for extension
- Dependency Inversion Principle: Depend upon abstraction and not upon concrete classes
- Principle of least knowledge (Only talk to your immediate friends): only invoke methods that belong to the object itself, to objects passed in as parameter, to any objects the method creates or instantiates (no methods on objects that were returned from calling other methods) and to any components of the object (has-a)
- Hollywood Principle: Don't call us, we call you
- Single Responsibility: a class should have only one reason to change
** Patterns
structural, behavioral, creational, concurrency patterns
- Strategy
  b
  defines a family of algorithms, encapsulates each one, and makes them interchangeable; algorithm can be modified independently from clients

- Observer
  b
  defines a one-to-many dependency between objects; all dependents are notified and udated automatically (push or pull by dependent)

- Decorator
  s
  a decorator attaches additional responsibilities to an object (the component) dynamically; the component can be used on its own or wrapped by a decorator; the decorator has-a component and implements the same interface as the component and adds new behavoirs

- Factory
  c
  a factory method handles object creation and encapsulates it in a subclass; the subclass decides which object to create; the method is only a interface in the base class, which can create a family of related or dependent products (abstract factory) or a single one

- Singleton
  c
  only one object is instanciated and a global point of access is provided

- Command
  b
  this pattern encapsulates a request as an object, thereby letting you parametrize other objects with different requests, queue or log requests, and support undoable operations

- Adapter/Wrapper/Translator
  s
  converts the interface of a class into another one the clients expect

- Facade
  s
  provides a unified interface to a set of interfaces in a subsystem. Facade defines a higher-level interface that makes the subsystem easier to use

- Template Method
  b
  defines the steps of an algorithm (skeleton) and allows subclasses to provide the implementation for one or more steps

- Iterator
  b
  an iterator provides a way to access elements of an aggregate object sequentially without exposing its underlying representation

- Composite
  s
  compose objects into tree structures to represent part-whole hierachies. Composite lets clients treat individual objects and composition of objects uniformly

- State
  b
  allows an object to alter its behavior when its internal state changes. The object will appear to change its class

- Proxy
  s
  provides a surrogate or placeholder for another object to control access to it

- Bridge
  s
  decouples an implementation from the interface, abstraction and implementation can be extended independently

- Builder
  c
  encapsulate the way a complex object is constructed and allows objects to be constructed in multistep

- Chain of Responsibility
  b
  decouples the sender and receiver of the request

- Flyweight
  s
  one instance of a class can be used to provide many virtual instances

- Mediator
  b
  centralize complex communications and control between related objects

- Memento
  b
  return an object to one of its previous states by keeping the saved state external from the key object

- Prototype
  c
  hide the complexities of making new instances of a given class from the client

- Visitor
  b
  add capabilities to a composite of objects if encapsulation is not important
** more design patterns
*** Repository Pattern
https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ff649690(v=pandp.10)?redirectedfrom=MSDN
- centralize data logic
- mediate between data and business layers
*** Unit of Work
https://martinfowler.com/eaaCatalog/unitOfWork.html
maintain list of affected objects by business transaction and coordinates the writing of changes

* Android
** gradle
*** version does not match for project
in the gradle/wrapper folder set the version in gradle-wrapper.properties,
then run gradlew.bat.
Gradle has to be synchronized after that in Android Studio
** debugging
*** adb shell
- access emulator
in the sdk folder, platform tools start 'adb shell'
- send location
adb.exe emu geo fix 100 200
- remove database
adb -e shell rm /data/data/com.example.package/databases/*.db
- remove app
adb -e uninstall com.example.package
*** evaluate command
in the Debug window key evaluate expression
*** logcat
- disable eglCodecCommon
eglCodecCommon: glUtilsParamSize: unknow param
happens due to emulator using host GPU
define filter with tag ^(?!eglCodecCommon)
** change visual style
   get zip from http://android-holo-colors.com/ with the style and copy it in res folder
   combine styles.xml and themes_apptheme.xml, only one style with name="AppTheme"
   parent should be compatible with sdk version
** avd
if the sdcard is just a link to somewhere: Tools -> Android ->
avd Manager set sdcard to enabled and maybe change disk size

* Javascript
** JsTestDriver
   startup: java -jar JsTestDriver-1.3.5.jar --port 42442
   configuration file: JsTestDriver.conf
   load:
   - src/Main.js
   test:
   - src-test/*.js
** misc functions
- arrays
  - contains element: .includes(ele)
  - Array(n) creates array with length n but no elements, cannot iterate over it
  - Array(n).fill() (see above) fills array also with elements
- get properties
  - Object.keys(obj)
  - for(var key in obj){ if (obj.hasOwnProperty(key)){...
- shallow copy/clone
  let cloned = {...orig}
- deep copy
  let deepCopy = JSON.parse(JSON.stringify(obj))
- assign properties/change properties
  Object.assign(objectToAssign, objectWithChangesNewProperties)
- base64
  new Buffer(client_id + ':' + client_secret).toString('base64')
*** insert dashes
function insertDashes(str) {
    zip= rows=>rows[0].map((_,c)=>rows.map(row=>row[c]))
    const str_as_arr = str.split('');
    let str_as_arr_shifted = str_as_arr.slice(1);
    str_as_arr_shifted.push(' ');
    const zipped = zip([str_as_arr,str_as_arr_shifted]);
    const with_dashes = zipped.map(chars => {
        if(chars[0] != ' ' && chars[1] != ' '){
            return  chars[0] + '-';
        }else{
            return chars[0];
        }
    })
    return with_dashes.join('');
}
* erlang
** shell
- current directory
pwd().
- switch directory
cd('d:/progra/erlang/scalabilitywitherlangotp/').
- compile module
c('modulename').
- call function
modulename:function().
* lua
** repl
- load file with dofile('somefile.lua')
- lua -l somefile (no file ending)
* cmake
generate CMakeLists.txt with dependencies, <cmake .> generates the project
* Containers
** k8s/kubernetes
*** commands kubectl
[[https://kubernetes.io/docs/reference/kubectl/cheatsheet/][cheatsheet]]
all commands should be possible for pods, services, deployments, namespaces, 
jobs.batch, cronjobs.batch, events, endpoints?

| api groups, v1 if none specified | kubectl api-resources                            |
| create pod/service               | kubectl create -f basic.yaml                     |
| deployment                       | kubectl create deployment firstpod --image=nginx |
| abbreviations                    | kubectl get deploy,rs,po,svc,ep,pv               |
| configmap                        | create configmap <name>                          |
| show log of pod                  | logs <pod>                                       |
**** get
separate resources with ,
| show nodes            | kubectl get nodes                                      |                            |
| pods, with IP         | kubectl get pods                                       | -o wide                    |
|                       | svc                                                    |                            |
| detailed output       | get jobs.batch <job> -o yaml                           |                            |
| pod with label        | get -l app=design2 pod/ get --selector app=design2 pod | when created by deployment |
| resource in namespace |                                                        | -n <namespace>             |
**** describe
| nodes information | kubectl describe nodes         |
| pod information   | kubectl describe pod <podname> |
**** delete
kubectl delete pod basicpod
**** exec
- first container in pod:
kubectl exec  -it <podname> -- /bin/bash
- with container name
kubectl exec  -it <podname> -c <containername> -- /bin/bash
**** edit
kubectl edit pod <podname>
**** expose
create service with port and type
**** scale
kubectl scale deployment <depl> --replicas=6
current-replicas or resource-version allow for validation before scaling
**** rollout
- history
- undo
**** replace
*** commands kubeadm
- kubeadm init
- kubeadm token create --print-join-command
- kubeadm reset
  revert changes by init/join
*** configuration
- expose port in pod
  containerPort
- expose pod to other nodes/pods with service
  selector in configuration matches pod label
  type NodePort to expose port from pod
- docker-compose.yaml
  convert to kubernetes yaml with kompose convert
** docker
https://docs.docker.com/install/linux/docker-ce/ubuntu/
add user to docker group (root!): sudo usermod -aG docker your-user, sg docker -c "bash"
*** commands
- build
  with Dockerfile in local directory, docker build -t <name> .
- image
  detailed info: docker image <name>
- images
  docker images
  docker pull ubuntu
- docker run <name>
  - detached, arbitrary port
    docker run --name mynginx1 -P -d nginx
  - with environment variable, remove after close
    docker run -e ASPNETCORE_URLS="http://*:80" -it --rm -p 12000:80 --name aspnetcore_sample aspnetapp
    mount volume -v /host/directory:/container/directory
  - optionally <cmd> which should be run
- container
  - docker container attach <name>
  - docker container list
  - get shell on container
    sudo docker container exec -it <name> /bin/bash
  - d c restart <container>
- docker network
  ls: show all networks, see inspect how to get it
- inspect
  show all information, e.g. networks
  - ip of container
    docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id
    docker inspect --format '{{ .NetworkSettings.IPAddress }}' <containername>
- log, for example for mysql, show stdout
  docker logs <containername>
- insecure access to registries
  edit /etc/docker/daemon.json
- volumes
  permanent storage, can be share between containers
  find mountpoint with inspect of container/volume
  to mount directory use -v /host/path:/container/path
*** docker-compose
- create yaml file, defining services, volumes, networks
- start with docker-compose up (-d detach)
- docker-compose stop (detatched)
- start shell with for service myapp
  docker-compose run --service-ports --rm myapp
  - run bash
    docker-compose run --service-ports --rm myapp bash
*** windows(old)
- set up host with virtualbox, hyperv only windows 10
- set env with eval $("D:\tools\Docker Toolbox\docker-machine.exe" env default)
- /d/tools/Docker\ Toolbox/docker.exe run busybox echo hello world
- /d/tools/Docker\ Toolbox/docker run -it --rm busybox
* mongodb
** basic
- ./mongod --dbpath "d:\data"
- mongo
> db
test
> db.test.find()
> db.test.save({a: 1})
> db.test.find()
>use admin
>db.shutdownServer()
** misc commands
- db.data.find().pretty()
- db.data.aggregate([{$project:{date: 1, numberOfEntries: {$size: "$entries"}}}])
- show dbs/collections
- db.data.find({"entries.duration": 4800}).pretty()
** update operators
$set, $push
https://docs.mongodb.com/manual/reference/operator/update/
* rust
** how to use nightly
see https://github.com/rust-lang-nursery/rustup.rs#working-with-nightly-rust,
the installed versions can be shown with <rustup toolchain list>, to add or set one
for the current directory <rustup override add/set nightly>
** set linker
https://github.com/rust-lang/rust/issues/37543
download llvm and set the linker in the .cargo/config file
[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"
** misc
- RUST_BACKTRACE=1 cargo run
- run example with cargo run --example <name>
- break build on msys after some errors: cargo build --color=always 2>&1 | head -n 10
** update toolchain/racer
- all toolchains
  rustup check
  rustup update
  - if component not available
    rustup component remove --toolchain nightly-x86_64-pc-windows-msvc clippy
- racer
  cargo +nightly install racer
* Inkscape
** coordinate system
no transform in layer http://www.inkscapeforum.com/viewtopic.php?f=16&t=12352&p=46140#p46140
new file -> delete layer -> create new one
* Go Golang
** godoc
run it on local package godoc -goroot="." <package name>, 
the source files have to be in a folder src/packack name
** profiling
create profile run with:
go test -v --bench . --benchmem -cpuprofile cpu.out
memory profiling is also possible
The output can be checked with
go tool pprof testbin.test cpu.out
e.g. top10, pdf
see https://blog.golang.org/profiling-go-programs
* epub & calibre
** remove drm from epubs:
(from https://apprenticealf.wordpress.com/2012/09/10/calibre-plugins-the-simplest-option-for-removing-most-ebook-drm/,
https://www.techradar.com/news/software/how-to-remove-ebook-drm-with-calibre-1291960)

download plugin for calibre https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.6.1

add in calibre under preferences -> plugins
* theory
** game theory
“The theory of games is a theory of decision-making.” This involves both how you feel you should make decisions, and how you actually make decisions, which is why understanding your motivations is valuable, because as Davis says, “your decisions are linked to your goals.”
*** goal focused
    See goals as a path to success
    Focus on the rewards you’ll gain when you achieve the outcome
    Be willing to take risks
    Feel comfortable jumping into opportunities, and work quickly
    Pay less attention to risks to your detriment, and be less prepared when things derail
*** prevention focused
See goals as important responsibilities to manage
Take care to outline potential risks
Strategize on process and progress to protect against risk
Stay vigilant about what you gain, and focus on keeping those gains
Be a problem-solver, and spend time on thorough analysis
Take a little extra time to get on the right path the first time
* octave
** basics
| identity matrix        | eye(i)                           |
| matrix                 | A = [12 21;23 32; 32 9]          |
| combining              | C = [A, A], C = [A;A]            |
| access elements        | A(1,:) , A(1:2,:)                |
| formating              | sprintf('dec %0.2f', 0.34234235) |
| show defined variables | who(s)                           |
| load/save file         | load x.dat, save file variable   |
| for loop               | for i = 1:10 .. end              |
* bash
** redirection
- stdout -> file
  programm > Datei.txt
- stderr -> file
  programm 2> Datei.txt
- stdout AND stderr -> file
  programm &> Datei.txt
- stdout -> file AND stderr -> file
  programm > Datei_stdout.txt 2> Datei_stderr.txt
- stdout -> stderr
  programm 1>&2
- stderr -> stdout
  programm 2>&1
| %                   | visible in terminal |        | visible in file |        | visible in file |           |
| Syntax              | StdOut              | StdErr | StdOut          | StdErr | file            |           |
|---------------------+---------------------+--------+-----------------+--------+-----------------+-----------|
| >                   | no                  | yes    | yes             | no     | overwrite       |           |
| >>                  | no                  | yes    | yes             | no     | append          |           |
| 2>                  | yes                 | no     | no              | yes    | overwrite       |           |
| 2>>                 | yes                 | no     | no              | yes    | append          |           |
| &>                  | no                  | no     | yes             | yes    | overwrite       |           |
| &>>                 | no                  | no     | yes             | yes    | append          |           |
| tee                 | yes                 | yes    | yes             | no     | overwrite       |           |
| tee -a              | yes                 | yes    | yes             | no     | append          |           |
| & tee (on fish 2>&1 | tee)                | yes    | yes             | yes    | yes             | overwrite |
| & tee -a            | yes                 | yes    | yes             | yes    | append          |           |
* fish
** init
- set path
set -x PATH in config.fish
could also be on command line:
set -U fish_user_paths $fish_user_paths /c/Users/nile/AppData/Local/Programs/Python/Python37/Scripts
** ssh-agent
https://github.com/danhper/fish-ssh-agent, https://github.com/ivakyb/fish_ssh_agent

wget https://raw.githubusercontent.com/danhper/fish-ssh-agent/master/functions/__ssh_agent_is_started.fish -P ~/.config/fish/functions/
wget https://raw.githubusercontent.com/danhper/fish-ssh-agent/master/functions/__ssh_agent_start.fish -P ~/.config/fish/functions/

add to config or source init.fish
#+begin_src fish
if test -z "$SSH_ENV"
    set -xg SSH_ENV $HOME/.ssh/environment
end

if not __ssh_agent_is_started
    __ssh_agent_start
end
#+end_src
** usage
- set environment variable for process
  env CASE_INSENSITIVE=1 cargo run
* python
- start pydoc server with pydoc -b
- start http server with python -m http.server
** setup virtual environment
https://docs.python.org/3/library/venv.html
python -m venv /path/to/new/virtual/environment
run/source 'activate' script in <venv>/bin/ folder
** exceptions
https://docs.python.org/3/library/exceptions.html#exception-hierarchy
** modules
- inspect e.g. for getting arguments inspect.signature(m)
* firefox
delete re-direct: in history right click site, Forget about this site:
will remove browse history and passwd etc.
* msys2/mingw64
** pacman
database lock is in /var/lib/pacman/db.lck
partial upgrades will not work, update everything with pacman -Syuu
** generate ssh keys
- check for existing key pair
  ls -al ~/.ssh
- create key
  ssh-keygen -t rsa -C 'comment'
- start agent, add certificate
  bash: eval $(ssh-agent -s),  -c for csh style shell
  ssh-add ~/.ssh/id_rsa
  or add 'AddKeysToAgent yes' to ~/.ssh/config
** create self-signed certificate
for https on localhost
https://letsencrypt.org/docs/certificates-for-localhost/
openssl req -x509 -out localhost.crt -keyout localhost.key  -newkey rsa:2048 -nodes -sha256  -subj '/CN=localhost' -extensions EXT -config <(printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
use openssl from /usr/bin, the one from /mingw64/bin fails with Can't open /proc/2406/fd/63 for reading, No such file or directory

** mintty
*** color schemas/font
are saved in /usr/share/mintty/themes/
font in ~/.minttyrc
* new installation
** fonts
- source code pro
- jetbrains mono
** utils
- putty
- emacs
- freecommander
* java
** compile
javac file1.java file2.java
or
javac *.java
-> generates fileX.class
** run
- java fileX
- with package com.somepackage
from src folder, *.class files in com/somepackage/
java com.somepackage.fileX (dot can be also /)
* gradle
** set up on linux
1. download
   gradle-6.3-all.zip, -bin does not include all libraries
2. path
   export PATH=$PATH:/home/student/java/gradle-6.3/bin
3. init
   gradle init --dsl kotlin
   -> creates gradlew and setting files

settings are saved at ~/.gradle, e.g. wrapper/dists
** configuration
build.gradle.kts
- plugins
  e.g. id("base") at top of file
- repositories
- dependencies

settings.gradle.kts
- projectname
- subprojects

** commands
| gradlew            |                                 |
|--------------------+---------------------------------|
| tasks              | list tasks which can be invoked |
| properties         |                                 |
| build              |                                 |
| run                |                                 |
| --warning-mode all |                                 |
| --scan             | creates overview                |
| --args='arg0 arg1' |                                 |
| --stop             | stop daemons                    |
|--------------------+---------------------------------|
* html
** basic html5
#+begin_src html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" href="css/style.css" />
        <title>The title</title>
    </head>
    <body>
        <script src="js/app.js"></script>
    </body>
</html>
#+end_src
** css
*** units
- em
- %
- vh,vm
  fill up only viewport, not parent
*** basic properties
- transform: scale, translate, ...
- transition
*** navbar (flex box)
add to parent div:
display:  flex;
justify-content: space-between; /*or center*/
margin: 0 5rem;
*** css grid (2D flex box)
set one element as grid:
.the_container{
    display: grid;
    grid-template-areas:
    'header header header'
    'post post related'
    'footer footer footer';
}
add elements with
.header-container{
    grid-area: header;
}
(other properties would be grid-template-columns where the width can be set, grid-template-rows,
set grid-column per element)
*** responsive web design
- media queries
- viewport
*** keyframes/animation
define @keyframes <name>, define there changes e.g.
- to {background: ...}
- 10%{..} 40%{..}
use it for element with animation-name, duration, fill-mode, delay
* encoding
http://www.unicode.org/versions/Unicode5.0.0/ch02.pdf
page 30
Use of a BOM is neither required nor recommended for UTF-8, but may be encountered in contexts where UTF-8 data is converted from other encoding forms that use a BOM or where the BOM is used as a UTF-8 signature.
* atlassian
** confluence
*** m2conf.py
python ~/projects/md_to_conf/md2conf.py import.md <space> -a <create page under>
