* SQL
** queries
- multicolumn search 
  select * from leadsets where (leadset, prodversion) in (select leadset, prodversion from orders where uniqnr = 172858)
- subselect with EXISTS
  select distinct(leadset) from leadset_attributes a1 where workstep = 5 and not exists (select 1 from leadset_attributes a2 where a2.Leadset = a1.Leadset and a2.ProdVersion = a1.ProdVersion and a2.Workstep = a1.Workstep and a2.Attribute = 2)
** glossary
 - DML data manupilation language
 - DDL data defintion language
** MySQL
run it in linux with /usr/sbin/rcmysql 
{start|stop|status|reload|restart|try-restart|force-reload}
or /etc/inti.d/mysql

| description       | command                                                      |
|-------------------+--------------------------------------------------------------|
| get all variables | SHOW VARIABLES (LIKE ...), of interest is e.g. character_set |
| time interval     | NOW() - INTERVAL 2 HOUR SECOND DAY etc.                      |
| create user       | CREATE USER 'jeffrey'@'localhost' IDENTIFIED BY 'mypass';    |
| use binary collate for case sensitive string comparison | select * from orders where leadset LIKE 's%' COLLATE utf8_bin                                                             |



*** InnoDB
- create index allows concurrent DML, see http://dev.mysql.com/doc/refman/5.6/en/innodb-create-index-overview.html
- MySQL will not use indexes if you query the wrong data type

** mysqldump
- export schema:
  mysqldump.exe -u diituser -p8932500 -h 142.120.60.114 -P 3306 -B diko --add-drop-database --add-drop-table -c --create-options --hex-blob --triggers --compress --quick --routines --no-data -r diko.sql

* Debugging
- disable just in time debugging with Visual Studio:
go to Tools -> Options -> Debugging -> Just-In-Time and disable VS as the JIT debugger.
(if not set in WER registry)
** WinDbg
- http://blogs.msdn.com/b/tess/archive/2008/02/04/net-debugging-demos-information-and-setup-instructions.aspx
- http://blogs.msdn.com/b/johan/archive/2007/01/11/how-to-install-windbg-and-get-your-first-memory-dump.aspx
*** General
  - all commands starting with . are from windbg
  - commands starting with ! are from some loaded extension
*** Installation
  - included in Debugging Tools for Windows
*** Setup
  - copy sos.dll from C:\Windows\Microsoft.NET\Framework\ (or Framework64) to windbg folder for .Net debugging
  - load it with .load sos
  - Create a folder where you want to cache all the symbol files. For example: "C:\Symbols"
  - Start windbg and open the dialogue to configure the symbol path by clicking File -> Symbol File Path
    srv*c:\symbols\public*http://msdl.microsoft.com/download/symbols
  - reload the dlls with .reload
  - if mscordacwks.dll cannot be loaded:
    this should show the load path:
    !sym noisy
    .symfix c:\mylocalsymcache
    .cordll -ve -u -l
    just copy the dll from the target pc to windbg folder and rename it to mscordacwks_AAA_AAA_2.0.50727.xxxx.dll,
    AAA is either x86 or AMD64, xxxx are the last digits of the version number
    lmv m mscorwks shows the include path for the dll
*** Commands
  | command          | description                           |
  |------------------+---------------------------------------|
  | .load            | load extension                        |
  | .loadby          | .loadby sos mscorwks                  |
  | .symfix          | load symbols                          |
  | .reload /f       | reload symbols                        |
  | !printexception  | show ex in crashdump                  |
  | !clrstack        | .net stack                            |
  | ~                | all threads                           |
  | !threads         | all managed threads (when sos loaded) |
  | ~<thread number> | activate thread                       |
  |                  |                                       |
*** Resources
https://blogs.msdn.microsoft.com/amb/2011/05/12/do-not-collect-32bit-process-dumps-with-64bit-task-manager/
ProcDump  https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx
** GDB
*** init file
    [[file:.gdbinit]
*** commands
- -args
 invoke program with arguments, specified with -
- break
 set breakpoint
- bt
 backtrace the calling stack
- c
 continue program
- n
 next line
- p
 print and/or set variable
- run
 run the program
- s, u
 step in, out
*** breakpoints
   - show with info break
   - disable <number>
*** pause process
   - Ctrl-C, in emacs Ctrl-C, Ctrl-C
     windows gui needs workaround in mingw console http://www.mingw.org/wiki/Workaround_for_GDB_Ctrl_C_Interrupt
*** print
   - p Function()
*** control
   - next next line in function
   - step next source code line
   - finish end of current function

* svn
** command line
*** Commands
  | command                                         | description                                   |
  |-------------------------------------------------+-----------------------------------------------|
  | svn diff -r... path                             | diff to revision ... in local copy            |
  | svnadmin dump --deltas <repo> > out.dump        | create dumpfile with deltas between revisions |
  | svnadmin load --force-uuid <newrepo> < out.dump | restore backup with unique identifier         |

*** diff for patch
- get diff from svn with diff -r rev1:rev2
  or diff -c rev

- emacs replace regex
  \(.*\)(revision 13286)^M -> \1(revision 13286)
  maybe the file has to be opened with (setq inhibit-eol-conversion t)
  
- run patch with
  patch -p0 < patchfile
* Windows
** DOS
*** compare files
comp: use with /N, else only filesize diff

*** registry
regsvr: register file in the windows registry, with /u unset key   
*** telnet
telnet client, call open $<$server$>$ to open a client, export DISPLAY IP:0
*** ftp
ftp client, login with ftp\_(IP), start with ftp $<$IP$>$, quit with bye, change to dir, bin, prompt, mget *;
*** cmd
  - start shell with C:$\backslash$WINDOWS$\backslash$system32$\backslash$cmd.exe /C "start" for multiple windows
  - start parameters: /V:ON: deactivate delayed resolving of variables, resolve them with !var!
*** nbtstat
find hostname from ip address: nbtstat -a
*** nslookup
    get all hosts from ip: nslookup ip
*** cacls
set access for file: cacls <file> /G <user:mode>, e.g. cacls dummy.txt /G Everyone:F; revert with /R
*** findstr
search for text in files with /S in subdirectories
*** net
    - show connections with net use
    - remove with net use /delete h:
    - connect with net use H: \\aphrodite\home * /USER:schwarzhuber
      * is prompt for password
** Office
- disable cursor animation
HKEY_Current_User\Software\Microsoft\Office\16.0\Common\Graphics
Name: DisableAnimations
Type: REG_DWORD
Data: 1 (hexadecimal)
*** Excel
Hyperlinks relativ setzen mit Datei -> Eigenschaften -> Zusammenfassung: Hyperlink
** Visual Studio
edit autoexp.dat for expanding and not stepping into in debugger
c:/Programme/Microsoft Visual Studio/Common/MSDev98/Bin/

TUString =<StringRep->Str,s>

[ExecutionControl] 
TUString::*=NoStepInto
CView::GetDocument=NoStepInto

c:/Programme/Microsoft Visual Studio 9.0/Common7/Packages/Debugger/

Makefile export:
wrong format for custom build of dll, use .$\backslash$LPPars not .LPPars\\
add path for DJGPP binaries

*** search not working

  No matching text found to look in. 
  Find was stopped in progress.
  
  Press ctrl + break

*** Visual Studio 2008
**** how to run it with the 6.0 compiler
C++ settings : 		
linker setttings: 	
delete the reference to the vcprojects default port vcproj file
project right click tool build order -> deselect manifest
options -> max number of project builds: 1
comman
**** Visual Studio “Find” results in “No files were found to look in.
     Find stopped progress
     the workaround (as many of you noted) is to press Ctrl+Scroll Lock, Ctrl+Break, or the Break key alone
*** Visual Studio 6.0
**** shortcuts

- LineCut, LineOpenBelow, 
- CharLeft, CharRight, LineEnd, LineStart, LineUp, LineDown
- FindBackwardDialog, Find, FindInFiles

**** Profiling
switch profiling on in Settings: Linker: enable profiling\\%
start profiling in the menu Build: Profil\\%
merge pbt and pbo files with prep /m $<name>$\\%
create file with plist /t $<name>$

**** Visual SourceSafe
     - disable with HKEY_CURRENT_USER\Software\Microsoft\DevStudio\6.0\Source Control\Disabled
*** emacs keybinding > 2008
   

    Download the Emacs emulation extension.

    Rename it from EmacsEmulations.vsix to EmacsEmulations.zip and unzip into a folder.

    Edit the <VisualStudio Version="10.0"> value on the extensions.vsixmanifest file (XML):

    <SupportedProducts>
        <VisualStudio Version="11.0">
        <Edition>Pro</Edition>
        </VisualStudio>
    </SupportedProducts>

    Note: Visual Studio 2013 works by setting Version="12.0". And VS Express can be used by setting <Edition>Express_All</Edition>
          Visual Studio 2015 "14.0"
    Zip the content inside the folder back up and rename it back to EmacsEmulations.vsix.
    Install the extension as the user who needs the bindings and not as administrator.
    Manually copy the Emacs.vsk file from the unzipped content of the extension to the Common7\IDE folder in the Visual Studio program directory (for which you will need elevated permissions).

** remote desktop
- local drives are mapped to //tsclient
- for copy + paste enable all fields in local resources, and restart rdpclip.exe
- speed up connection with 15bit, background turned off
- back to fullscreen: ctrl alt break
- send ctrl alt del: ctrl alt end
** Win
   - disable task manager
     HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
     "Shell"="%ExePath%"
   - start cmd box as administrator
     runas /noprofile /user:mymachine\administrator cmd
     or with domain  /user:mydomain\admin
   - disable task manager
     Key: Software\Microsoft\Windows\CurrentVersion\Policies\System
     Name: DisableTaskMgr
     Type: REG_DWORD
     Value: 1=Enablethis key, that is DISABLE TaskManager
   - set group policy with gpedit.msc
     to set it up only for non-admin users (not XP): load mmc.exe, add gpedit as snapin
     select in Browse Dialog the users: non-Admin
   - policies are saved in the registry in 
     HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\
     HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\
   - edit registry of other user
     mark HKEY_USERS, File -> Load Hive
     load file ntuser.dat from user folder
     unload after edit
   - run PerfMon for performance monitoring
   - add items to send to senden an menu in documents and settings:user:sendto
   - Nicht genügend Serverspeicher vorhanden
     Not working: 
     HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management "LargeSystemCache" "1"
     HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\ "Size" "3"
     HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\ "IRPStackSize" "50"
   - kill processes
     list with tasklist
     Taskkill /IM chrome.exe /F
   - default reply, no messagebox
     HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Error Message Instrument : EnableDefaultReply = 0
** Gadgets
*** basics
    - default gadgets are in C:\Program Files\Windows Sidebar\Gadgets
      copy one and rename folder and gadget.xml name
      zip and rename to .gadget
      install: did not work
    - folder %UserProfile%\AppData\Local\Microsoft\Windows Sidebar\Gadgets
** Visual Basic
   escape " with "", for a linebreak use \_
** .NET
PerformanceCounter cannot be used: in PerfMon all counters in Windows Workflow Foundation are not selectable; this seems to be the same reason why the resume layout after the EndInit of the PerformanceCounter fails 

** Services
- start and control services with the \textbf{sc} command
- start net
  install a .Net service with installutil
  install: sc create CAO-COPLSapSebastian binPath= "C:\usr\schwarzhuber\COPL\bin\sap_gw.exe /ServiceName=CAO-COPLSapSebastian /gwFile=\"C:\usr\schwarzhuber\COPL\config\SAP_GW\SapGateway.xml\""
  change: sc config binPath= ...
- set start timeout
  1. Click Start, click Run, type regedit, and then click OK.
  2. Locate and then click the following registry subkey:
     HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control
  3. In the right pane, locate the ServicesPipeTimeout entry.
     Note: If the ServicesPipeTimeout entry does not exist, you must create it. To do this, follow these steps:
     On the Edit menu, point to New, and then click DWORD Value.
     Type ServicesPipeTimeout, and then press ENTER. 
  4. Right-click ServicesPipeTimeout, and then click Modify.
  5. Click Decimal, type 60000, and then click OK.
     This value represents the time in milliseconds before a service times out.
  6. Restart the computer.
** IIS

   -logfiles c:/inetpub/logs, set in IIS configuration, enable logging in Programs and Features -> turn Features on/off
   - HTTP Error 500.19
     0x80070005: Click the Security tab, and then click Edit.
     Click Add.
     In the Enter the object names to select box, type computername\IIS_IUSRS, click Check Names, and then click OK.
     Click to select the Read check box, and then click OK.
** disable telemetry data gathering
   http://superuser.com/questions/972501/how-to-stop-microsoft-from-gathering-telemetry-data-from-windows-7-8-and-8-1

** Wireshark
- Wireshark can't actually capture local packets on windows XP due to the nature of the windows TCP stack. When packets are sent and received on the same machine they don't seem to cross the network boundary that wireshark monitors.

    However there is a way around this, you can route the local traffic out via your network gateway (router) by setting up a (temporary) static route on your windows XP machine.

    Say your XP IP address is 192.168.0.2 and your gateway (router) address is 192.168.0.1 you could run the following command from windows XP command line to force all local traffic out and back across the network boundary, so wireshark could then track the data (note that wireshark will report packets twice in this scenario, once when they leave your pc and once when they return).

    route add 192.168.0.2 mask 255.255.255.255 192.168.0.1 metric 1

  ! First save the route for the ip address and add it afterwards again!
  add -p to make the change persistent

- filter for ip address and destination
  ip.addr == 142.120.20.133 & ip.dst == 142.120.60.20
** WER
set in HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting
*** path to dumps
\Debug: StoreLocation
or
%LOCALAPPDATA%\CrashDumps

** Sysinternals
*** check signing
sigcheck -a d:\tmp\DomainGroupsTester.exe
** Outlook
- set mail as read
File → Options → Advanced
Outlook panes section, click Reading Pane
Mark items as read when viewed in the Reading Pane and set interval
* Thunderbird
** new mail
- switch text/html in new mail with create + shift

** virtual folder
   search for keywords -> create as virtual folder

* ruby
** ruby style
- callbacks
  def do_stuff(a,b,c)
    sum=a+b+c
    yield sum #<- can be checked with block_given?
  end

  #call with:
  do_stuff(a,b,c){|status_code| puts "did #{a}, ... #{status_code}"}
** basic
- find method
  <instance>.method(<:method_name>).source_location
*** rspec
    - run with rspec path/to/file.rb

** rails
speed up webrick without ReverseDNSLookup
*** basic
**** main layout
   <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   will produce an error, solution:

   http://stackoverflow.com/questions/12520456/execjsruntimeerror-on-windows-trying-to-follow-rubytutorial

My friend was attempting a Rails tutorial on Win 8 RTM a few months ago and ran into this error. Not sure if this issue exists in Windows 7 as well, but this may help.

Options:

1) Removing //= require_tree . / Ignoring the issue - As ColinR stated above, this line should not be causing an issue in the first place. There is an actual problem with ExecJS working properly with the JavaScript runtime on your system and removing this line is just ignoring that fact.

2) Installing Node.js / Running away - Many people seem to just end up installing Node.js and using that instead of the JavaScript runtime already on their system. While that is a valid option, it also requires additional software and only avoids the original issue, which is that ExecJS is not working properly with the JavaScript runtime already on your system. If the existing JavaScript runtime on your system is supposed to work, why not make it work instead of installing more software? According to the ExecJS creator, the runtime already built into Windows is in fact supported...

    ExecJS lets you run JavaScript code from Ruby. It automatically picks the best runtime available to evaluate your JavaScript program, then returns the result to you as a Ruby object.

    ExecJS supports these runtimes:

        therubyracer - Google V8 embedded within Ruby
        therubyrhino - Mozilla Rhino embedded within JRuby
        Node.js
        Apple JavaScriptCore - Included with Mac OS X
        Microsoft Windows Script Host (JScript)

    (from github.com/sstephenson/execjs#execjs )

3) Actually fixing the issue / Learning - Use the knowledge of options 1 and 2 to search for other solutions. I can't tell you how many webpages I closed upon seeing options 1 or 2 was the accepted solution before actually finding information about the root issue we were having. The only reason we kept looking was that we couldn't believe the Rails team would (1) insert a line of code in every scaffold generated project that caused an issue, or (2) require that we install additional software just to run that default line of code. And so we eventually arrived at a fix for our root issue (your miles may vary).

The Fix that worked for us: On the system having issues, find ExecJS's runtimes.rb file. It looks like this. Make a copy of the found file for backup. Open the original runtimes.rb for editing. Find the section that starts with the line JScript = ExternalRuntime.new(. In that section, on the line containing :command => "cscript //E:jscript //Nologo //U", - remove the //U only. Then on the line containing :encoding => 'UTF-16LE' # CScript with //U returns UTF-16LE - change UTF-16LE to UTF-8 . Save the changes to the file. This section of the file should now read:

JScript = ExternalRuntime.new(
    :name        => "JScript",
    :command     => "cscript //E:jscript //Nologo",
    :runner_path => ExecJS.root + "/support/jscript_runner.js",
    :encoding    => 'UTF-8' # CScript with //U returns UTF-16LE
)

Next, stop then restart your Rails server and refresh the page in your browser that produced the original error. Hopefully the page loads without error now. Here's the ExecJS issue thread where we originally posted our results: https://github.com/sstephenson/execjs/issues/81#issuecomment-9892952

If this did not fix the issue, you can always overwrite the modified runtimes.rb with the backup copy you (hopefully) made and everything will be back to square one. In that case, consider option 3 and keep searching. Let us know what eventually works for you.. unless it's removing the require_tree or installing node.js, there's plenty of that going around already. :)


*** running old rails
**** problem with bluecloth 2.2.0


     Run gem install bluecloth -v '2.2.0' if you haven't already

     Apply this patch on bluecloth.h file, on my machine it is located in

     H:\Ruby193\lib\ruby\gems\1.9.1\gems\bluecloth-2.2.0\ext\bluecloth.h

     Go to bluecloth 2.2.0 directory, for example

     H:\Ruby193\lib\ruby\gems\1.9.1\gems\bluecloth-2.2.0

     Run rake gem (this may require to install some additional gems).

     Then you should see .gem file created in

     H:\Ruby193\lib\ruby\gems\1.9.1\gems\bluecloth-2.2.0\pkg\bluecloth-2.2.0.gem

     Open this directory and install the patched gem:

     gem install bluecloth-2.2.0.gem --platform=ruby

     => will not work, but gem install works after that
**** problem with libv8
    used by therubyracer
    NOT: gem install libv8 -v '3.16.14.1' -- --with-system-v8
    take it out with: 
    gem 'therubyracer', "~>0.11", :platform => :ruby
    :platform :ruby will install only on unix
**** wrong version of rake
     use bundle exec rake
* VMWare
** disable beep: To turn it off for only one session, do the following:

   1. Click Start
   2. Click Run
   3. In the run box type
      net stop beep

To turn off the beep permanently, do the following:

1. Click Start
   2. Click Run
   3. In the run box type
      sc config beep start= disabled (please note the space after the = !!)

To change the status of the beep again, type any of the following in the run box:

    * sc config beep start= boot (for loading device driver by the boot loader)
    * sc config beep start= system (for loading device driver by the kernel initialization)
    * sc config beep start= auto (for starting service automatically at startup. Even when no one logs on)
    * sc config beep start= demand (for starting service manually (default, when no start parameter is specified))
    * sc config beep start= disabled (completely disables the service)
    * sc config beep start= delayed-auto (for starting service after other “auto” services are started)

** To disable ThinPrint on a View client, change the values of these registry keys as indicated:

    HKEY_CURRENT_USER Software VMware, Inc. VMware VDM Client RDP Settings RedirectPrinters = false
    HKLM SOFTWARE thinPrint TPAutoConnect ConnectToClient = DISABLED 

Notes:

    If the keys do not exist, create them with values of type STRING.
    You may have to reboot the client for the changes to take effect.
    This method disables ThinPrint on the client side only. The View Desktop can use ThinPrint to print when you connect to it from a different client computer. 

Additional Information
You may also disable ThinPrint within the virtual desktop by disabling the TP AutoConnect Service and TP VC Gateway Service.

To disable ThinPrint within the virtual desktop:

    Log in to the virtual machine.
    Open the Services console.
    Right-click the TP AutoConnect service.
    Click Properties.
    Under Service status, click Stop.
    Click the Startup type and click Disabled.
    Click OK.
    Repeat steps 1-7 for the TP VC Gateway service.
    Close the Services console. 
** Host USB device connection disabled
Try right clicking on one of the USB hubs and looking at the driver details. If usbfilter.sys is listed then open HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{36FC9E60-C465-11CF-8056-444553540000} and delete the UpperFilter, usbfilter pair. 
restart some times after change
* C#
** folders
*** exe.config files
- XP: C:\Dokumente und Einstellungen\sebastian\Lokale Einstellungen\Anwendungsdaten\DiIT\
- Win7: C:\Users\schwarzhuber\AppData\Local\DiIT
** NUnit
*** basisc
    - console runner
      run with nunit-console.exe dllToTest
      creates result file in directory
** Uri Escaping
   pairs Uri.EscapeDataString and HttpUtility.UrlEncode,
   Uri.EscapeUriString and HttpUtility.UrlPathEncode

   Uri better, uses uppercase hex encoding
   see also http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding
** .Net Framework
*** exception in webclient
The specified registry key does not exist
Registry location: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework  
DWORD (32-bit) Value name: LegacyWPADSupport
Value data: 0
* emacs
64 bit build at http://sourceforge.net/projects/emacsbinw64/
** customize and start files
   - site-start.el is loaded first, cancel with --no-site-file

** build emacs
*** old verision
**** tools
    - mingw32: gcc, make (rename from mingw32-make)
    - GnuWin Packages: CoreUtils, FindUtils, libxpm (with src)
**** prebuild
    - copy simx.h to include dir
**** configure
    - configure.bat --with-gcc --cflags -ID:/tools/GnuWin32/include/ --without-png --without-jpeg --without-tiff --without-gif
**** make
*** new version
**** git repo
     - git clone git://git.savannah.gnu.org/emacs.git emacs
**** tools
     - mingw32: developer toolkit 
     - add the fstab file in the msys etc directory, http://www.mingw.org/wiki/Getting_Started#toc2
     - remove msys-texinfo and use the one from http://sourceforge.net/projects/ezwinports/files/
     - pckconfig from http://www.gtk.org/download/win32.php
**** prebuild
     - run ./autogen.sh
       then dos2unix configure.ac
       the again ./autogen.sh
**** build
     - release: CFLAGS='-O2' ../emacs/configure --prefix=/d/progra/c/emacsrelease
** modes
*** artist mode
    for drawing asccii art
*** org mode
**** ditaa
     - activate babel with ditaa
     - download ditaa.jar and install java jre to run
*** *Messages*
    set size of buffer with (setq message-log-max 5000)
*** hex with hexl-mode
     or hexl-find-file instead of find-file
*** which-function-mode
    display the current function name
** format
*** C++ Code
   - the C Label Minimum Indentation has to be set to 4 (with override style settings):
   (c-syntactic-indentation t) this will read the format from c-offsets-alist
   if no indentation is done, set it manually with C-c C-o
*** encoding
    change encoding of buffer with C-x RET f coding RET
*** carriage return
    (setq inhibit-eol-conversion t), otherwise windows file has only ^J in text mode
    https://lists.gnu.org/archive/html/help-gnu-emacs/2005-12/msg00548.html
** fonts
   - show all faces with M-x list-faces-display -> customize
   font family is fndry and fmly from xfontsel

   my options:'(default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :family "misc-fixed"))))
** Windows
   Here's a Windows tip that I find invaluable for tools such as editors. Rather than associating Emacs with the particular file types you want to edit with it (because you may want to associate another application with them), add Emacs to your SendTo menu.

   - Open the folder where you installed Emacs and navigate to the bin directory.
   - Select runemacs.exe, click mouse-button-2 and select Create Shortcut. The new shortcut appears, highlighted.
   - Click mouse-button-2 again and select Cut (you're going to move it).
   - Move to the Start button and click mouse-button-2 to open the menu.
   - Select Explore, which should open Windows Explorer to the Start Menu folder.
    In the navigation pane, select the SendTo folder (usually just above the Start Menu folder) to open it.
    Within the SendTo folder, click mouse-button-2 and select Paste to insert the runemacs.exe shortcut.
    Rename the shortcut, if you like.

** misc commands
*** file layout
    show regex in new buffer
    M-x occur

*** search for control characters
    C-q C-(control char), ^@ with C-Space, ^? with Backspace
*** environment variables
    (getenv "DS\_LOC") (setenv "DS\_LOC" "FTN")
*** set encoding
    C-x C-m f
*** remove complete line
    flush-line (opposite of keep-line)

*** replace in files
    M-x find-name-dired: you will be prompted for a root directory and a filename pattern.
    Press t to "toggle mark" for all files found.
    Press Q for "Query-Replace in Files...": you will be prompted for query/substitution regexps.
*** execute shell command
(shell-command-to-string "hostname")
*** get char info
    describe-char for character at point

*** pretty print xml
in sgml mode select region and run sgml-pretty-print
** Visual Studio in emacs
*** format
    for visual studio set (Basic Offset = 4) in programming languages C and (indent tabs mode = off) in editing indent. 
    Format is set in list

** elisp
   - you cannot execute buffer functions in scratch
   - CAR and CDR (could-er) are the two slots of a cons cell (an ordered pair) which refer to some lisp objects
   - numbers in a keymap represent decimal values of ascii control characters:\\%

   Dec. Code & Character
   9 & Tab 
   13 & carriage return 
   17 & C-q
   24 & C-# XXX: 
   27 & Esc

** SQL Mode
in windows add the bin directory for mysql to the exec-path

** CSharp Mode

   when used in Linux some warning pops up because of uninitalize varible flymake:
   change is-flymake-loaded with check fboundp to boundp
   
   newer version of csharp-mode:
   (let ((is-flymake-enabled
   (and (boundp 'flymake-mode)
   flymake-mode)))

** Windows
   Here's a Windows tip that I find invaluable for tools such as editors. Rather than associating Emacs with the particular file types you want to edit with it (because you may want to associate another application with them), add Emacs to your SendTo menu.

   - Open the folder where you installed Emacs and navigate to the bin directory.
   - Select runemacs.exe, click mouse-button-2 and select Create Shortcut. The new shortcut appears, highlighted.
   - Click mouse-button-2 again and select Cut (you're going to move it).
   - Move to the Start button and click mouse-button-2 to open the menu.
   - Select Explore, which should open Windows Explorer to the Start Menu folder.
    In the navigation pane, select the SendTo folder (usually just above the Start Menu folder) to open it.
    Within the SendTo folder, click mouse-button-2 and select Paste to insert the runemacs.exe shortcut.
    Rename the shortcut, if you like.

** org mode
*** export only visible area
    C-c C-e C-v
*** odt export
    - export #+OPTIONS: H:10 num:t for template file, save as ott, use with #+ODT_STYLES_FILE: "D:/usr/schwarzhuber/projects/mine/example.ott"
    - set font in template under options, writer, default font only for this document
    - filename can be set with #+PROPERTY: EXPORT_FILE_NAME 2015_06_11_Neue_Funktionen_2, only if export subtree is used, C-s, change of property has to be activated with C-c C-c
*** misc
    - export table to csv with Tbl -> Export to File
    - file link
      file:<path to file> with two [ and two ]

* Linux
** commands
- back quote command substitution: runs one command on the other, like ll `find . -print`. Could also be \$(cmd)

- list commands: run command1 \&\& then command2, if command1 returns 0, can also be used with ||, ; (sequentially), \& (asynchron)

- brace expansion: cmd {1,2,$\ldots$} every option in the braces separated by a comma gets extend and the cmd is run with the whole string (cp filename{,.bak})

- font show all fonts with xfontsel

- info show online help with 'info'

- find find . -follow -name "*.cfg" -exec grep -inHl 'mtbl' {} \; i: case insensitive, l: name of input file, H: filename, n: line number

- proc use 'proc show ZWN\_{}nprd' to start an agent in its directory or 'proc start YUL\_que'

- mounting use mount for list of mounted devices, mounting table under /etc/fstab

- ifconfig is in /sbin/, lists all ip addresses; (ipconfig)

- xev show key commands

- prompt display variable set through PS1
- setxkbmap set the keyboard mapping to de, us etc. (see next item)
- loadkeys load keys globally from lib, e.g. us -> us.map.gz, use showkeys to show them, only with access to /dev/console (see above item)
- basename/dirname chop path strings to names

- concatenate files to one
  cat file* >> toFile
  find . -type f -name '*.txt' -exec cat {} + >> output.file : + starts only one process

- append newline to end of file
  perl -0777 -i.original -pe 's/END;\n\$\$/END;\n\$\$\n/igs' Update*
- show ip
  ip addr show
- telnet
  telnet <ip> <port>
- show blocked ports
  sudo /sbin/iptables -L -n
- show listening ports
  sudo netstat -tulpn
- diff two folders
  diff -ru src/ /f/restlib/src/
- ssh
  use 'ssh 142.120.61.41 -l root' to connect with root
** window managers
- old ones mwn, twn

- fvwm descendant from twn

- icewm also a lightweight wm with profiles
* Vagrant
** config file
   - add local box with file:///C:/Users/...
   - port forwarding with config.vm.network :forwarded_port, guest: 3000, host: 3000 
* cygwin
** turn off beep
   home directory .inputrc
   set bell-style none
* mono
** build
   - csproj files with xbuild /p:Configuration=Debug x.csproj
** csproj
   - ToolsVersion sets framework
   - Bootstrapper entries are dependencies for click once setups 
* Tags
** setup
   run find . -name "*.cs" -exec "D:\tools\emacs24.3\bin\etags.exe" -a {} ;
   creates a TAGS file
** use
   visit-tags-table for TAGS file to use
   search tags with M-., C-u M-., C-u - M-.

* vi
** commands
   - unset an option with set no<option>
   - show whitespace: set list
   - set background color hi: Normal guibg=Grey90
** colorscheme
   save it in .vim/colors
   add it in .vimrc with colorscheme <name>
** bell
   set it to visual bell
   set noeb vb t_vb=

* git
** basics
   - .gitignore for files which should not be shown in untracked files
** commands
   - add: add files, redo if changed, -A adds all files
   - commit: commit -m 'message', -a for all unstaged changes
   - diff
     cached shows diff with staged files
     <commit> <commit> for difference between two commits
   - log
     show last i commits with -n i
   - add to last commit
     git commit --amend --no-edit
     no-edit flag re-uses the last commit message
   - rename case insensitive folders
     git mv foldername tempname && git mv tempname folderName
   - create mbox file from commits, first commit not included
     git format-patch --stdout 7c46acb1..c8ee6573 > 01.3_15.3.patch

* powershell
** commands
   - Load a dll
     Add-Type -Path .$\backslash$DiIT.Misc.dll
   - get methods + members: [int] | Get-Member
   - call static methods with [int]::MaxValue
   - pipe to fl (Format-List) to get all properties
   - call method: $i = 30, $i.GetHashCode()
   - create a class
     $a = New-Object DiIT.Misc.LeadsetPV("sfasdf/122/3")
   - parameter switch
     set it with colon -parameter:$true
   - open registry key remotely
     $Reg = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey('LocalMachine', "coplds1")
     $RegKey= $Reg.OpenSubKey("SOFTWARE\DiIT\copl\Database")
   - get unique values from a csv file
     $leadsets = Import-Csv .\sft.csv -Delimiter ';'
     $dupLeadsets = $leadsets | Group {$_.Leadset} | where {$_.Count -gt 1}
     $dupLeadsets | select count, name > duplicate_leadsets.csv
   - get path for executable
     (Get-Command notepad.exe).Path
*** format files output
    get-item .\* -Include *.dll, *.exe | where-object {$_.VersionInfo.CompanyName -eq "DiIT"} | sort {$_.VersionInfo.FileVersion} | ForEach-Object {$_.VersionInfo.FileVersion + " " + $_.Name}
* Redmine
  webrick has problems with reverse dns lookup, turn it off
** svn integration
   - enable SCM in Administration -> Repositories
   - enable WS for repository management
     use Web Service to udpate svn log on every commit
   - set the repository for every project
   - run ruby /path_to_redmine/redmine/script/rails runner "Repository.fetch_changesets" -e production
     to get the complete log the first time
     first call svn from the command line to set the svn user and password
   - set post-commit hook
* LibreOffice
** convert to pdf
   *LibreOffice should not run*
   in Windows only - not --
   soffice.exe -convert-to pdf Neue_Funktionen.odt -headless
   
** calc
*** sort/filter
    Data->Filter->AutoFilter
** impress
*** master
right click -> edit master
*** defaults
F11 (styles and formatting): image and presentation styles
-> right click edit styles
* Office
** VBA
- 
** Excel
*** settings
- set colon ; as delimiter for csv: Control Panel -> Region and Language -> Additional Settings
*** commands
- open vba editor: Alt+F11
*** Formulas
- references
  relativ: A1
  absolut: $A$1
  partial: $A1, A$1
- included in range, count
=ZÄHLENWENN($A$1:$A$110;E186)
* GDB
** init file
   [[file:.gdbinit]
** commands
- -args
 invoke program with arguments, specified with -
- break
 set breakpoint
- bt
 backtrace the calling stack
- c
 continue program
- n
 next line
- p
 print and/or set variable
- run
 run the program
- s, u
 step in, out
* Gimp
  Create Transparent Background: Add Alpha Channel in Layers, select Select By Color Tool, click background, delete it
* msbuild
** structure
   a Project has different PropertyGroup, ItemGroup and Target elements
*** simple one
    <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
    <AssemblyName>MoqTests</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
    <Compile Include="Tests.cs"/>
    </ItemGroup>
    <Target Name="Build">
    <Csc Sources="@(Compile)" OutputAssembly="$(AssemblyName).exe"/>
    </Target>
    </Project>
*** extended
    <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
    where targets are defined
** references
   - http://msdn.microsoft.com/en-us/library/dd393574%28v=vs.100%29.aspx
   - http://msdn.microsoft.com/en-us/library/dd576348%28v=vs.100%29.aspx
   - Target Files: WindowsInstallationPath\Microsoft.NET\Framework\<version>\
* common
** start bios win8
   shift-click restart: advanced boot options
* GnuWin32
  - run download.bat
  - run install <directory>

* OOP
** Basics and Principles
- Encapsulate what varies
- Favor composition over inheritance: has-a is better than is-a; changeable during runtime
- Program to an interface not an implementation: model behavior in new abstract class, reusable and modifyable
- Strive for loosely coupled designs: objects can interact, but have very little knowledge of each other
- Open Closed Principle: Classes should be closed for modification but open for extension
- Dependency Inversion Principle: Depend upon abstraction and not upon concrete classes
- Principle of least knowledge (Only talk to your immediate friends): only invoke methods that belong to the object itself, to objects passed in as parameter, to any objects the method creates or instantiates (no methods on objects that were returned from calling other methods) and to any components of the object (has-a)
- Hollywood Principle: Don't call us, we call you
- Single Responsibility: a class should have only one reason to change
** Patterns
- Strategy
 defines a family of algorithms, encapsulates each one, and makes them interchangeable; algorithm can be modified independently from clients

- Observer
 defines a one-to-many dependency between objects; all dependents are notified and udated automatically (push or pull by dependent)

- Decorator
 a decorator attaches additional responsibilities to an object (the component) dynamically; the component can be used on its own or wrapped by a decorator; the decorator has-a component and implements the same interface as the component and adds new behavoirs

- Factory
 a factory method handles object creation and encapsulates it in a subclass; the subclass decides which object to create; the method is only a interface in the base class, which can create a family of related or dependent products (abstract factory) or a single one

- Singleton
 only one object is instanciated and a global point of access is provided

- Command
 this pattern encapsulates a request as an object, thereby letting you parametrize other objects with different requests, queue or log requests, and support undoable operations

- Adapter
 converts the interface of a class into another one the clients expect

- Facade
 provides a unified interface to a set of interfaces in a subsystem. Facade defines a higher-level interface that makes the subsystem easier to use

- Template Method
 defines the steps of an algorithm (skeleton) and allows subclasses to provide the implementation for one or more steps

- Iterator
 an iterator provides a way to access elements of an aggregate object sequentially without exposing its underlying representation

- Composite
 compose objects into tree structures to represent part-whole hierachies. Composite lets clients treat individual objects and composition of objects uniformly

- State
 allows an object to alter its behavior when its internal state changes. The object will appear to change its class

- Proxy
 provides a surrogate or placeholder for another object to control access to it

- Bridge
 decouples an implementation from the interface, abstraction and implementation can be extended independently

- Builder
 encapsulate the way a complex object is constructed and allows objects to be constructed in multistep

- Chain of Responsibility
 decouples the sender and receiver of the request

- Flyweight
 one instance of a class can be used to provide many virtual instances

- Mediator
 centralize complex communications and control between related objects

- Memento
 return an object to one of its previous states by keeping the saved state external from the key object

- Prototype
 hide the complexities of making new instances of a given class from the client

- Visitor
 add capabilities to a composite of objects if encapsulation is not important


* Android
** gradle
*** version does not match for project
in the gradle/wrapper folder set the version in gradle-wrapper.properties,
then run gradlew.bat.
Gradle has to be synchronized after that in Android Studio
** debugging
*** adb shell
- access emulator
in the sdk folder, platform tools start 'adb shell'
- send location
adb.exe emu geo fix 100 200
*** evaluate command
in the Debug window key evaluate expression
*** logcat
- disable eglCodecCommon
eglCodecCommon: glUtilsParamSize: unknow param
happens due to emulator using host GPU
define filter with tag ^(?!eglCodecCommon)
** change visual style
   get zip from http://android-holo-colors.com/ with the style and copy it in res folder
   combine styles.xml and themes_apptheme.xml, only one style with name="AppTheme"
   parent should be compatible with sdk version
** avd
if the sdcard is just a link to somewhere: Tools -> Android ->
avd Manager set sdcard to enabled and maybe change disk size

* Javascript
** JsTestDriver
   startup: java -jar JsTestDriver-1.3.5.jar --port 42442
   configuration file: JsTestDriver.conf
   load:
   - src/Main.js
   test:
   - src-test/*.js

* erlang
** shell
- current directory
pwd().
- switch directory
cd('d:/progra/erlang/scalabilitywitherlangotp/').
- compile module
c('modulename').
- call function
modulename:function().
* lua
** repl
- load file with dofile('somefile.lua')
- lua -l somefile (no file ending)
* cmake
generate CMakeLists.txt with dependencies, <cmake .> generates the project
* docker
** windows
- set up host with virtualbox, hyperv only windows 10
- set env with eval $("D:\tools\Docker Toolbox\docker-machine.exe" env default)
- /d/tools/Docker\ Toolbox/docker.exe run busybox echo hello world
- /d/tools/Docker\ Toolbox/docker run -it --rm busybox
* mongodb
** basic
- ./mongod --dbpath "d:\data"
- mongo
> db
test
> db.test.find()
> db.test.save({a: 1})
> db.test.find()
>use admin
>db.shutdownServer()
** misc commands
- db.data.find().pretty()
- db.data.aggregate([{$project:{date: 1, numberOfEntries: {$size: "$entries"}}}])
- show dbs/collections
- db.data.find({"entries.duration": 4800}).pretty()
** update operators
$set, $push
https://docs.mongodb.com/manual/reference/operator/update/
* rust
** misc
- RUST_BACKTRACE=1 cargo run
- run example with cargo run --example <name>
* Inkscape
** coordinate system
no transform in layer http://www.inkscapeforum.com/viewtopic.php?f=16&t=12352&p=46140#p46140
new file -> delete layer -> create new one
